#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum Mnemonic {
    AAA,
    AAD,
    AAM,
    AAS,
    ADC,
    ADCX,
    ADD,
    ADDPD,
    ADDPS,
    ADDSD,
    ADDSS,
    ADDSUBPD,
    ADDSUBPS,
    ADOX,
    AESDEC,
    AESDECLAST,
    AESENC,
    AESENCLAST,
    AESIMC,
    AESKEYGENASSIST,
    AND,
    ANDN,
    ANDNPD,
    ANDNPS,
    ANDPD,
    ANDPS,
    ARPL,
    BEXTR,
    BLENDPD,
    BLENDPS,
    BLENDVPD,
    BLENDVPS,
    BLSI,
    BLSMSK,
    BLSR,
    BNDCL,
    BNDCN,
    BNDCU,
    BNDLDX,
    BNDMK,
    BNDMOV,
    BNDSTX,
    BOUND,
    BSF,
    BSR,
    BSWAP,
    BT,
    BTC,
    BTR,
    BTS,
    BZHI,
    CALL,
    CBW,
    CDQ,
    CDQE,
    CLAC,
    CLC,
    CLD,
    CLFLUSH,
    CLFLUSHOPT,
    CLI,
    CLTS,
    CLWB,
    CMC,
    CMOVA,
    CMOVAE,
    CMOVB,
    CMOVBE,
    CMOVC,
    CMOVE,
    CMOVG,
    CMOVGE,
    CMOVL,
    CMOVLE,
    CMOVNA,
    CMOVNAE,
    CMOVNB,
    CMOVNBE,
    CMOVNC,
    CMOVNE,
    CMOVNG,
    CMOVNGE,
    CMOVNL,
    CMOVNLE,
    CMOVNO,
    CMOVNP,
    CMOVNS,
    CMOVNZ,
    CMOVO,
    CMOVP,
    CMOVPE,
    CMP,
    CMPPD,
    CMPPS,
    CMPS,
    CMPSB,
    CMPSD,
    CMPSQ,
    CMPSS,
    CMPSW,
    CMPXCHG,
    CMPXCHG16B,
    CMPXCHG8B,
    COMISD,
    COMISS,
    CPUID,
    CQO,
    CRC32,
    CVTDQ2PD,
    CVTDQ2PS,
    CVTPD2DQ,
    CVTPD2PI,
    CVTPD2PS,
    CVTPI2PD,
    CVTPI2PS,
    CVTPS2DQ,
    CVTPS2PD,
    CVTPS2PI,
    CVTSD2SI,
    CVTSD2SS,
    CVTSI2SD,
    CVTSI2SS,
    CVTSS2SD,
    CVTSS2SI,
    CVTTPD2DQ,
    CVTTPD2PI,
    CVTTPS2DQ,
    CVTTPS2PI,
    CVTTSD2SI,
    CVTTSS2SI,
    CWD,
    CWDE,
    DAA,
    DAS,
    DEC,
    DIV,
    DIVPD,
    DIVPS,
    DIVSD,
    DIVSS,
    DPPD,
    DPPS,
    EMMS,
    ENTER,
    EXTRACTPS,
    F2XM1,
    FABS,
    FADD,
    FADDP,
    FBLD,
    FBSTP,
    FCHS,
    FCLEX,
    FCMOVB,
    FCMOVBE,
    FCMOVE,
    FCMOVNB,
    FCMOVNBE,
    FCMOVNE,
    FCMOVNU,
    FCMOVU,
    FCOM,
    FCOMI,
    FCOMIP,
    FCOMP,
    FCOMPP,
    FCOS,
    FDECSTP,
    FDIV,
    FDIVP,
    FDIVR,
    FDIVRP,
    FFREE,
    FIADD,
    FICOM,
    FICOMP,
    FIDIV,
    FIDIVR,
    FILD,
    FIMUL,
    FINCSTP,
    FINIT,
    FIST,
    FISTP,
    FISTTP,
    FISUB,
    FISUBR,
    FLD,
    FLD1,
    FLDCW,
    FLDENV,
    FLDL2E,
    FLDL2T,
    FLDLG2,
    FLDLN2,
    FLDPI,
    FLDZ,
    FMUL,
    FMULP,
    FNCLEX,
    FNINIT,
    FNOP,
    FNSAVE,
    FNSTCW,
    FNSTENV,
    FNSTSW,
    FPATAN,
    FPREM,
    FPREM1,
    FPTAN,
    FRNDINT,
    FRSTOR,
    FSAVE,
    FSCALE,
    FSIN,
    FSINCOS,
    FSQRT,
    FST,
    FSTCW,
    FSTENV,
    FSTP,
    FSTSW,
    FSUB,
    FSUBP,
    FSUBR,
    FSUBRP,
    FTST,
    FUCOM,
    FUCOMI,
    FUCOMIP,
    FUCOMP,
    FUCOMPP,
    FWAIT,
    FXAM,
    FXCH,
    FXRSTOR,
    FXRSTOR64,
    FXSAVE,
    FXSAVE64,
    FXTRACT,
    FYL2X,
    FYL2XP1,
    HADDPD,
    HADDPS,
    HLT,
    HSUBPD,
    HSUBPS,
    IDIV,
    IMUL,
    IN,
    INC,
    INS,
    INSB,
    INSD,
    INSERTPS,
    INSW,
    INT,
    INTO,
    INVD,
    INVLPG,
    INVPCID,
    IRET,
    IRETD,
    IRETQ,
    JA,
    JAE,
    JB,
    JBE,
    JC,
    JCXZ,
    JE,
    JECXZ,
    JG,
    JGE,
    JL,
    JLE,
    JMP,
    JNA,
    JNAE,
    JNB,
    JNBE,
    JNC,
    JNE,
    JNG,
    JNGE,
    JNL,
    JNLE,
    JNO,
    JNP,
    JNS,
    JNZ,
    JO,
    JP,
    JPE,
    JPO,
    JRCXZ,
    JS,
    JZ,
    KADDB,
    KADDD,
    KADDQ,
    KADDW,
    KANDB,
    KANDD,
    KANDNB,
    KANDND,
    KANDNQ,
    KANDNW,
    KANDQ,
    KANDW,
    KMOVB,
    KMOVD,
    KMOVQ,
    KMOVW,
    KNOTB,
    KNOTD,
    KNOTQ,
    KNOTW,
    KORB,
    KORD,
    KORQ,
    KORTESTB,
    KORTESTD,
    KORTESTQ,
    KORTESTW,
    KORW,
    KSHIFTLB,
    KSHIFTLD,
    KSHIFTLQ,
    KSHIFTLW,
    KSHIFTRB,
    KSHIFTRD,
    KSHIFTRQ,
    KSHIFTRW,
    KTESTB,
    KTESTD,
    KTESTQ,
    KTESTW,
    KUNPCKBW,
    KUNPCKDQ,
    KUNPCKWD,
    KXNORB,
    KXNORD,
    KXNORQ,
    KXNORW,
    KXORB,
    KXORD,
    KXORQ,
    KXORW,
    LAHF,
    LAR,
    LDDQU,
    LDMXCSR,
    LDS,
    LEA,
    LEAVE,
    LES,
    LFENCE,
    LFS,
    LGDT,
    LGS,
    LIDT,
    LLDT,
    LMSW,
    LOCK,
    LODS,
    LODSB,
    LODSD,
    LODSQ,
    LODSW,
    LOOP,
    LOOPE,
    LOOPNE,
    LSL,
    LSS,
    LTR,
    LZCNT,
    MASKMOVDQU,
    MASKMOVQ,
    MAXPD,
    MAXPS,
    MAXSD,
    MAXSS,
    MFENCE,
    MINPD,
    MINPS,
    MINSD,
    MINSS,
    MONITOR,
    MOV,
    MOVAPD,
    MOVAPS,
    MOVBE,
    MOVD,
    MOVDDUP,
    MOVDQ2Q,
    MOVDQA,
    MOVDQU,
    MOVHLPS,
    MOVHPD,
    MOVHPS,
    MOVLHPS,
    MOVLPD,
    MOVLPS,
    MOVMSKPD,
    MOVMSKPS,
    MOVNTDQ,
    MOVNTDQA,
    MOVNTI,
    MOVNTPD,
    MOVNTPS,
    MOVNTQ,
    MOVQ,
    MOVQ2DQ,
    MOVS,
    MOVSB,
    MOVSD,
    MOVSHDUP,
    MOVSLDUP,
    MOVSQ,
    MOVSS,
    MOVSW,
    MOVSX,
    MOVSXD,
    MOVUPD,
    MOVUPS,
    MOVZX,
    MPSADBW,
    MUL,
    MULPD,
    MULPS,
    MULSD,
    MULSS,
    MULX,
    MWAIT,
    NEG,
    NOP,
    NOT,
    OR,
    ORPD,
    ORPS,
    OUT,
    OUTS,
    OUTSB,
    OUTSD,
    OUTSW,
    PABSB,
    PABSD,
    PABSW,
    PACKSSDW,
    PACKSSWB,
    PACKUSDW,
    PACKUSWB,
    PADDB,
    PADDD,
    PADDQ,
    PADDSB,
    PADDSW,
    PADDUSB,
    PADDUSW,
    PADDW,
    PALIGNR,
    PAND,
    PANDN,
    PAUSE,
    PAVGB,
    PAVGW,
    PBLENDVB,
    PBLENDW,
    PCLMULQDQ,
    PCMPEQB,
    PCMPEQD,
    PCMPEQQ,
    PCMPEQW,
    PCMPESTRI,
    PCMPESTRM,
    PCMPGTB,
    PCMPGTD,
    PCMPGTQ,
    PCMPGTW,
    PCMPISTRI,
    PCMPISTRM,
    PDEP,
    PEXT,
    PEXTRB,
    PEXTRD,
    PEXTRQ,
    PEXTRW,
    PHADDD,
    PHADDSW,
    PHADDW,
    PHMINPOSUW,
    PHSUBD,
    PHSUBSW,
    PHSUBW,
    PINSRB,
    PINSRD,
    PINSRQ,
    PINSRW,
    PMADDUBSW,
    PMADDWD,
    PMAXSB,
    PMAXSD,
    PMAXSW,
    PMAXUB,
    PMAXUD,
    PMAXUW,
    PMINSB,
    PMINSD,
    PMINSW,
    PMINUB,
    PMINUD,
    PMINUW,
    PMOVMSKB,
    PMOVSXBD,
    PMOVSXBQ,
    PMOVSXBW,
    PMOVSXDQ,
    PMOVSXWD,
    PMOVSXWQ,
    PMOVZXBD,
    PMOVZXBQ,
    PMOVZXBW,
    PMOVZXDQ,
    PMOVZXWD,
    PMOVZXWQ,
    PMULDQ,
    PMULHRSW,
    PMULHUW,
    PMULHW,
    PMULLD,
    PMULLW,
    PMULUDQ,
    POP,
    POPA,
    POPAD,
    POPCNT,
    POPF,
    POPFD,
    POPFQ,
    POR,
    PREFETCHNTA,
    PREFETCHT0,
    PREFETCHT1,
    PREFETCHT2,
    PREFETCHW,
    PREFETCHWT1,
    PSADBW,
    PSHUFB,
    PSHUFD,
    PSHUFHW,
    PSHUFLW,
    PSHUFW,
    PSIGNB,
    PSIGND,
    PSIGNW,
    PSLLD,
    PSLLDQ,
    PSLLQ,
    PSLLW,
    PSRAD,
    PSRAW,
    PSRLD,
    PSRLDQ,
    PSRLQ,
    PSRLW,
    PSUBB,
    PSUBD,
    PSUBQ,
    PSUBSB,
    PSUBSW,
    PSUBUSB,
    PSUBUSW,
    PSUBW,
    PTEST,
    PTWRITE,
    PUNPCKHBW,
    PUNPCKHDQ,
    PUNPCKHQDQ,
    PUNPCKHWD,
    PUNPCKLBW,
    PUNPCKLDQ,
    PUNPCKLQDQ,
    PUNPCKLWD,
    PUSH,
    PUSHA,
    PUSHAD,
    PUSHF,
    PUSHFD,
    PUSHFQ,
    PXOR,
    RCL,
    RCPPS,
    RCPSS,
    RCR,
    RDFSBASE,
    RDGSBASE,
    RDMSR,
    RDPID,
    RDPKRU,
    RDPMC,
    RDRAND,
    RDSEED,
    RDTSC,
    RDTSCP,
    RET,
    ROL,
    ROR,
    RORX,
    ROUNDPD,
    ROUNDPS,
    ROUNDSD,
    ROUNDSS,
    RSM,
    RSQRTPS,
    RSQRTSS,
    SAHF,
    SAL,
    SAR,
    SARX,
    SBB,
    SCAS,
    SCASB,
    SCASD,
    SCASQ,
    SCASW,
    SETA,
    SETAE,
    SETB,
    SETBE,
    SETC,
    SETE,
    SETG,
    SETGE,
    SETL,
    SETLE,
    SETNA,
    SETNAE,
    SETNB,
    SETNBE,
    SETNC,
    SETNE,
    SETNG,
    SETNGE,
    SETNL,
    SETNLE,
    SFENCE,
    SGDT,
    SHA1MSG1,
    SHA1MSG2,
    SHA1NEXTE,
    SHA1RNDS4,
    SHA256MSG1,
    SHA256MSG2,
    SHA256RNDS2,
    SHL,
    SHLD,
    SHLX,
    SHR,
    SHRD,
    SHRX,
    SHUFPD,
    SHUFPS,
    SIDT,
    SLDT,
    SMSW,
    SQRTPD,
    SQRTPS,
    SQRTSD,
    SQRTSS,
    STAC,
    STC,
    STD,
    STI,
    STMXCSR,
    STOS,
    STOSB,
    STOSD,
    STOSQ,
    STOSW,
    STR,
    SUB,
    SUBPD,
    SUBPS,
    SUBSD,
    SUBSS,
    SWAPGS,
    SYSCALL,
    SYSENTER,
    SYSEXIT,
    SYSRET,
    TEST,
    TZCNT,
    UCOMISD,
    UCOMISS,
    UD0,
    UD1,
    UD2,
    UNPCKHPD,
    UNPCKHPS,
    UNPCKLPD,
    UNPCKLPS,
    VADDPD,
    VADDPS,
    VADDSD,
    VADDSS,
    VADDSUBPD,
    VADDSUBPS,
    VAESDEC,
    VAESDECLAST,
    VAESENC,
    VAESENCLAST,
    VAESIMC,
    VAESKEYGENASSIST,
    VALIGND,
    VALIGNQ,
    VANDNPD,
    VANDNPS,
    VANDPD,
    VANDPS,
    VBLENDMPD,
    VBLENDMPS,
    VBLENDPD,
    VBLENDPS,
    VBLENDVPD,
    VBLENDVPS,
    VBROADCASTF128,
    VBROADCASTF32X2,
    VBROADCASTF32X4,
    VBROADCASTF64X2,
    VBROADCASTI128,
    VBROADCASTI32x2,
    VBROADCASTI32X4,
    VBROADCASTI32X8,
    VBROADCASTI64X2,
    VBROADCASTI64X4,
    VBROADCASTSD,
    VBROADCASTSS,
    VCMPPD,
    VCMPPS,
    VCMPSD,
    VCMPSS,
    VCOMISD,
    VCOMISS,
    VCOMPRESSPD,
    VCOMPRESSPS,
    VCVTDQ2PD,
    VCVTDQ2PS,
    VCVTPD2DQ,
    VCVTPD2PS,
    VCVTPD2QQ,
    VCVTPD2UDQ,
    VCVTPD2UQQ,
    VCVTPH2PS,
    VCVTPS2DQ,
    VCVTPS2PD,
    VCVTPS2PH,
    VCVTPS2QQ,
    VCVTPS2UDQ,
    VCVTPS2UQQ,
    VCVTQQ2PD,
    VCVTQQ2PS,
    VCVTSD2SI,
    VCVTSD2SS,
    VCVTSD2USI,
    VCVTSI2SD,
    VCVTSI2SS,
    VCVTSS2SD,
    VCVTSS2SI,
    VCVTSS2USI,
    VCVTTPD2DQ,
    VCVTTPD2QQ,
    VCVTTPD2UDQ,
    VCVTTPD2UQQ,
    VCVTTPS2DQ,
    VCVTTPS2QQ,
    VCVTTPS2UDQ,
    VCVTTPS2UQQ,
    VCVTTSD2SI,
    VCVTTSD2USI,
    VCVTTSS2SI,
    VCVTTSS2USI,
    VCVTUDQ2PD,
    VCVTUDQ2PS,
    VCVTUQQ2PD,
    VCVTUQQ2PS,
    VCVTUSI2SD,
    VCVTUSI2SS,
    VDBPSADBW,
    VDIVPD,
    VDIVPS,
    VDIVSD,
    VDIVSS,
    VDPPD,
    VDPPS,
    VERR,
    VERW,
    VEXP2PD,
    VEXP2PS,
    VEXPANDPD,
    VEXPANDPS,
    VEXTRACTF128,
    VEXTRACTF32x4,
    VEXTRACTF64x4,
    VEXTRACTI128,
    VEXTRACTI32x4,
    VEXTRACTI64x4,
    VEXTRACTPS,
    VFIXUPIMMPD,
    VFIXUPIMMPS,
    VFIXUPIMMSD,
    VFIXUPIMMSS,
    VFMADD132PD,
    VFMADD132PS,
    VFMADD132SD,
    VFMADD132SS,
    VFMADD213PD,
    VFMADD213PS,
    VFMADD213SD,
    VFMADD213SS,
    VFMADD231PD,
    VFMADD231PS,
    VFMADD231SD,
    VFMADD231SS,
    VFMADDSUB132PD,
    VFMADDSUB132PS,
    VFMADDSUB213PD,
    VFMADDSUB213PS,
    VFMADDSUB231PD,
    VFMADDSUB231PS,
    VFMSUB132PD,
    VFMSUB132PS,
    VFMSUB132SD,
    VFMSUB132SS,
    VFMSUB213PD,
    VFMSUB213PS,
    VFMSUB213SD,
    VFMSUB213SS,
    VFMSUB231PD,
    VFMSUB231PS,
    VFMSUB231SD,
    VFMSUB231SS,
    VFMSUBADD132PD,
    VFMSUBADD132PS,
    VFMSUBADD213PD,
    VFMSUBADD213PS,
    VFMSUBADD231PD,
    VFMSUBADD231PS,
    VFNMADD132PD,
    VFNMADD132PS,
    VFNMADD132SD,
    VFNMADD132SS,
    VFNMADD213PD,
    VFNMADD213PS,
    VFNMADD213SD,
    VFNMADD213SS,
    VFNMADD231PD,
    VFNMADD231PS,
    VFNMADD231SD,
    VFNMADD231SS,
    VFNMSUB132PD,
    VFNMSUB132PS,
    VFNMSUB132SD,
    VFNMSUB132SS,
    VFNMSUB213PD,
    VFNMSUB213PS,
    VFNMSUB213SD,
    VFNMSUB213SS,
    VFNMSUB231PD,
    VFNMSUB231PS,
    VFNMSUB231SD,
    VFNMSUB231SS,
    VFPCLASSPD,
    VFPCLASSPS,
    VFPCLASSSD,
    VFPCLASSSS,
    VGATHERDPD,
    VGATHERDPS,
    VGATHERPF0DPD,
    VGATHERPF0DPS,
    VGATHERPF0QPD,
    VGATHERPF0QPS,
    VGATHERPF1DPD,
    VGATHERPF1DPS,
    VGATHERPF1QPD,
    VGATHERPF1QPS,
    VGATHERQPD,
    VGATHERQPS,
    VGETEXPPD,
    VGETEXPPS,
    VGETEXPSD,
    VGETEXPSS,
    VGETMANTPD,
    VGETMANTPS,
    VGETMANTSD,
    VGETMANTSS,
    VHADDPD,
    VHADDPS,
    VHSUBPD,
    VHSUBPS,
    VINSERTF128,
    VINSERTI128,
    VINSERTPS,
    VLDDQU,
    VLDMXCSR,
    VMASKMOVDQU,
    VMASKMOVPD,
    VMASKMOVPS,
    VMAXPD,
    VMAXPS,
    VMAXSD,
    VMAXSS,
    VMINPD,
    VMINPS,
    VMINSD,
    VMINSS,
    VMOVAPD,
    VMOVAPS,
    VMOVD,
    VMOVDDUP,
    VMOVDQA,
    VMOVDQA32,
    VMOVDQA64,
    VMOVDQU,
    VMOVDQU16,
    VMOVDQU32,
    VMOVDQU64,
    VMOVDQU8,
    VMOVHLPS,
    VMOVHPD,
    VMOVHPS,
    VMOVLHPS,
    VMOVLPD,
    VMOVLPS,
    VMOVMSKPD,
    VMOVMSKPS,
    VMOVNTDQ,
    VMOVNTDQA,
    VMOVNTPD,
    VMOVNTPS,
    VMOVQ,
    VMOVSD,
    VMOVSHDUP,
    VMOVSLDUP,
    VMOVSS,
    VMOVUPD,
    VMOVUPS,
    VMPSADBW,
    VMULPD,
    VMULPS,
    VMULSD,
    VMULSS,
    VORPD,
    VORPS,
    VPABSB,
    VPABSD,
    VPABSW,
    VPACKSSDW,
    VPACKSSWB,
    VPACKUSDW,
    VPACKUSWB,
    VPADDB,
    VPADDD,
    VPADDQ,
    VPADDSB,
    VPADDSW,
    VPADDUSB,
    VPADDUSW,
    VPADDW,
    VPALIGNR,
    VPAND,
    VPANDD,
    VPANDN,
    VPANDND,
    VPANDNQ,
    VPANDQ,
    VPAVGB,
    VPAVGW,
    VPBLENDD,
    VPBLENDMB,
    VPBLENDMD,
    VPBLENDMQ,
    VPBLENDMW,
    VPBLENDVB,
    VPBLENDW,
    VPBROADCASTB,
    VPBROADCASTD,
    VPBROADCASTMB2Q,
    VPBROADCASTMW2D,
    VPBROADCASTQ,
    VPBROADCASTW,
    VPCLMULQDQ,
    VPCMPB,
    VPCMPD,
    VPCMPEQB,
    VPCMPEQD,
    VPCMPEQQ,
    VPCMPEQW,
    VPCMPESTRI,
    VPCMPESTRM,
    VPCMPGTB,
    VPCMPGTD,
    VPCMPGTQ,
    VPCMPGTW,
    VPCMPISTRI,
    VPCMPISTRM,
    VPCMPQ,
    VPCMPUB,
    VPCMPUD,
    VPCMPUQ,
    VPCMPUW,
    VPCMPW,
    VPCOMPRESSD,
    VPCOMPRESSQ,
    VPCONFLICTD,
    VPCONFLICTQ,
    VPERM2F128,
    VPERM2I128,
    VPERMD,
    VPERMI2D,
    VPERMI2PD,
    VPERMI2PS,
    VPERMI2Q,
    VPERMI2W,
    VPERMILPD,
    VPERMILPS,
    VPERMPD,
    VPERMPS,
    VPERMQ,
    VPERMT2D,
    VPERMT2PD,
    VPERMT2PS,
    VPERMT2Q,
    VPERMT2W,
    VPERMW,
    VPEXPANDD,
    VPEXPANDQ,
    VPEXTRB,
    VPEXTRD,
    VPEXTRQ,
    VPEXTRW,
    VPGATHERDD,
    VPGATHERDQ,
    VPGATHERQD,
    VPGATHERQQ,
    VPHADDD,
    VPHADDSW,
    VPHADDW,
    VPHMINPOSUW,
    VPHSUBD,
    VPHSUBSW,
    VPHSUBW,
    VPINSRB,
    VPINSRD,
    VPINSRQ,
    VPINSRW,
    VPLZCNTD,
    VPLZCNTQ,
    VPMADDUBSW,
    VPMADDWD,
    VPMASKMOVD,
    VPMASKMOVQ,
    VPMAXSB,
    VPMAXSD,
    VPMAXSW,
    VPMAXUB,
    VPMAXUD,
    VPMAXUQ,
    VPMAXUW,
    VPMINSB,
    VPMINSD,
    VPMINSQ,
    VPMINSW,
    VPMINUB,
    VPMINUD,
    VPMINUQ,
    VPMINUW,
    VPMOVB2M,
    VPMOVD2M,
    VPMOVDB,
    VPMOVDW,
    VPMOVM2B,
    VPMOVM2D,
    VPMOVM2Q,
    VPMOVM2W,
    VPMOVMSKB,
    VPMOVQ2M,
    VPMOVQB,
    VPMOVQD,
    VPMOVQW,
    VPMOVSDB,
    VPMOVSDW,
    VPMOVSQB,
    VPMOVSQD,
    VPMOVSQW,
    VPMOVSWB,
    VPMOVSXBD,
    VPMOVSXBQ,
    VPMOVSXBW,
    VPMOVSXDQ,
    VPMOVSXWD,
    VPMOVSXWQ,
    VPMOVUSDB,
    VPMOVUSDW,
    VPMOVUSQB,
    VPMOVUSQD,
    VPMOVUSQW,
    VPMOVUSWB,
    VPMOVW2M,
    VPMOVWB,
    VPMOVZXBD,
    VPMOVZXBQ,
    VPMOVZXBW,
    VPMOVZXDQ,
    VPMOVZXWD,
    VPMOVZXWQ,
    VPMULDQ,
    VPMULHRSW,
    VPMULHUW,
    VPMULHW,
    VPMULLD,
    VPMULLQ,
    VPMULLW,
    VPMULUDQ,
    VPOR,
    VPORD,
    VPORQ,
    VPROLD,
    VPROLQ,
    VPROLVD,
    VPROLVQ,
    VPRORD,
    VPRORQ,
    VPRORVD,
    VPRORVQ,
    VPSADBW,
    VPSCATTERDD,
    VPSCATTERDQ,
    VPSCATTERQD,
    VPSCATTERQQ,
    VPSHUFB,
    VPSHUFD,
    VPSHUFHW,
    VPSHUFLW,
    VPSIGNB,
    VPSIGND,
    VPSIGNW,
    VPSLLD,
    VPSLLDQ,
    VPSLLQ,
    VPSLLVD,
    VPSLLVQ,
    VPSLLVW,
    VPSLLW,
    VPSRAD,
    VPSRAQ,
    VPSRAVD,
    VPSRAVQ,
    VPSRAVW,
    VPSRAW,
    VPSRLD,
    VPSRLDQ,
    VPSRLQ,
    VPSRLVD,
    VPSRLVQ,
    VPSRLVW,
    VPSRLW,
    VPSUBB,
    VPSUBD,
    VPSUBQ,
    VPSUBSB,
    VPSUBSW,
    VPSUBUSB,
    VPSUBUSW,
    VPSUBW,
    VPTERNLOGD,
    VPTERNLOGQ,
    VPTEST,
    VPTESTMB,
    VPTESTMD,
    VPTESTMQ,
    VPTESTMW,
    VPTESTNMB,
    VPTESTNMD,
    VPTESTNMQ,
    VPTESTNMW,
    VPUNPCKHBW,
    VPUNPCKHDQ,
    VPUNPCKHQDQ,
    VPUNPCKHWD,
    VPUNPCKLBW,
    VPUNPCKLDQ,
    VPUNPCKLQDQ,
    VPUNPCKLWD,
    VPXOR,
    VPXORD,
    VPXORQ,
    VRANGEPD,
    VRANGEPS,
    VRANGESD,
    VRANGESS,
    VRCP14PD,
    VRCP14PS,
    VRCP14SD,
    VRCP14SS,
    VRCP28PD,
    VRCP28PS,
    VRCP28SD,
    VRCP28SS,
    VRCPPS,
    VRCPSS,
    VREDUCEPD,
    VREDUCEPS,
    VREDUCESD,
    VREDUCESS,
    VRNDSCALEPD,
    VRNDSCALEPS,
    VRNDSCALESD,
    VRNDSCALESS,
    VROUNDPD,
    VROUNDPS,
    VROUNDSD,
    VROUNDSS,
    VRSQRT14PD,
    VRSQRT14PS,
    VRSQRT14SD,
    VRSQRT14SS,
    VRSQRT28PD,
    VRSQRT28PS,
    VRSQRT28SD,
    VRSQRT28SS,
    VRSQRTPS,
    VRSQRTSS,
    VSCALEFPD,
    VSCALEFPS,
    VSCALEFSD,
    VSCALEFSS,
    VSCATTERDPD,
    VSCATTERDPS,
    VSCATTERPF0DPD,
    VSCATTERPF0DPS,
    VSCATTERPF0QPD,
    VSCATTERPF0QPS,
    VSCATTERPF1DPD,
    VSCATTERPF1DPS,
    VSCATTERPF1QPD,
    VSCATTERPF1QPS,
    VSCATTERQPD,
    VSCATTERQPS,
    VSHUFF32x4,
    VSHUFF64x2,
    VSHUFI32x4,
    VSHUFI64x2,
    VSHUFPD,
    VSHUFPS,
    VSQRTPD,
    VSQRTPS,
    VSQRTSD,
    VSQRTSS,
    VSTMXCSR,
    VSUBPD,
    VSUBPS,
    VSUBSD,
    VSUBSS,
    VTESTPD,
    VTESTPS,
    VUCOMISD,
    VUCOMISS,
    VUNPCKHPD,
    VUNPCKHPS,
    VUNPCKLPD,
    VUNPCKLPS,
    VXORPD,
    VXORPS,
    VZEROALL,
    VZEROUPPER,
    WAIT,
    WBINVD,
    WRFSBASE,
    WRGSBASE,
    WRMSR,
    WRPKRU,
    XABORT,
    XACQUIRE,
    XADD,
    XBEGIN,
    XCHG,
    XEND,
    XGETBV,
    XLAT,
    XLATB,
    XOR,
    XORPD,
    XORPS,
    XRELEASE,
    XRSTOR,
    XRSTOR64,
    XRSTORS,
    XRSTORS64,
    XSAVE,
    XSAVE64,
    XSAVEC,
    XSAVEC64,
    XSAVEOPT,
    XSAVEOPT64,
    XSAVES,
    XSAVES64,
    XSETBV,
    XTEST,
}

impl Mnemonic {
    pub fn parse(val: &str) -> Result<Mnemonic, ()> {
        match val {
            "AAA" => Ok(Mnemonic::AAA),
            "AAD" => Ok(Mnemonic::AAD),
            "AAM" => Ok(Mnemonic::AAM),
            "AAS" => Ok(Mnemonic::AAS),
            "ADC" => Ok(Mnemonic::ADC),
            "ADCX" => Ok(Mnemonic::ADCX),
            "ADD" => Ok(Mnemonic::ADD),
            "ADDPD" => Ok(Mnemonic::ADDPD),
            "ADDPS" => Ok(Mnemonic::ADDPS),
            "ADDSD" => Ok(Mnemonic::ADDSD),
            "ADDSS" => Ok(Mnemonic::ADDSS),
            "ADDSUBPD" => Ok(Mnemonic::ADDSUBPD),
            "ADDSUBPS" => Ok(Mnemonic::ADDSUBPS),
            "ADOX" => Ok(Mnemonic::ADOX),
            "AESDEC" => Ok(Mnemonic::AESDEC),
            "AESDECLAST" => Ok(Mnemonic::AESDECLAST),
            "AESENC" => Ok(Mnemonic::AESENC),
            "AESENCLAST" => Ok(Mnemonic::AESENCLAST),
            "AESIMC" => Ok(Mnemonic::AESIMC),
            "AESKEYGENASSIST" => Ok(Mnemonic::AESKEYGENASSIST),
            "AND" => Ok(Mnemonic::AND),
            "ANDN" => Ok(Mnemonic::ANDN),
            "ANDNPD" => Ok(Mnemonic::ANDNPD),
            "ANDNPS" => Ok(Mnemonic::ANDNPS),
            "ANDPD" => Ok(Mnemonic::ANDPD),
            "ANDPS" => Ok(Mnemonic::ANDPS),
            "ARPL" => Ok(Mnemonic::ARPL),
            "BEXTR" => Ok(Mnemonic::BEXTR),
            "BLENDPD" => Ok(Mnemonic::BLENDPD),
            "BLENDPS" => Ok(Mnemonic::BLENDPS),
            "BLENDVPD" => Ok(Mnemonic::BLENDVPD),
            "BLENDVPS" => Ok(Mnemonic::BLENDVPS),
            "BLSI" => Ok(Mnemonic::BLSI),
            "BLSMSK" => Ok(Mnemonic::BLSMSK),
            "BLSR" => Ok(Mnemonic::BLSR),
            "BNDCL" => Ok(Mnemonic::BNDCL),
            "BNDCN" => Ok(Mnemonic::BNDCN),
            "BNDCU" => Ok(Mnemonic::BNDCU),
            "BNDLDX" => Ok(Mnemonic::BNDLDX),
            "BNDMK" => Ok(Mnemonic::BNDMK),
            "BNDMOV" => Ok(Mnemonic::BNDMOV),
            "BNDSTX" => Ok(Mnemonic::BNDSTX),
            "BOUND" => Ok(Mnemonic::BOUND),
            "BSF" => Ok(Mnemonic::BSF),
            "BSR" => Ok(Mnemonic::BSR),
            "BSWAP" => Ok(Mnemonic::BSWAP),
            "BT" => Ok(Mnemonic::BT),
            "BTC" => Ok(Mnemonic::BTC),
            "BTR" => Ok(Mnemonic::BTR),
            "BTS" => Ok(Mnemonic::BTS),
            "BZHI" => Ok(Mnemonic::BZHI),
            "CALL" => Ok(Mnemonic::CALL),
            "CBW" => Ok(Mnemonic::CBW),
            "CDQ" => Ok(Mnemonic::CDQ),
            "CDQE" => Ok(Mnemonic::CDQE),
            "CLAC" => Ok(Mnemonic::CLAC),
            "CLC" => Ok(Mnemonic::CLC),
            "CLD" => Ok(Mnemonic::CLD),
            "CLFLUSH" => Ok(Mnemonic::CLFLUSH),
            "CLFLUSHOPT" => Ok(Mnemonic::CLFLUSHOPT),
            "CLI" => Ok(Mnemonic::CLI),
            "CLTS" => Ok(Mnemonic::CLTS),
            "CLWB" => Ok(Mnemonic::CLWB),
            "CMC" => Ok(Mnemonic::CMC),
            "CMOVA" => Ok(Mnemonic::CMOVA),
            "CMOVAE" => Ok(Mnemonic::CMOVAE),
            "CMOVB" => Ok(Mnemonic::CMOVB),
            "CMOVBE" => Ok(Mnemonic::CMOVBE),
            "CMOVC" => Ok(Mnemonic::CMOVC),
            "CMOVE" => Ok(Mnemonic::CMOVE),
            "CMOVG" => Ok(Mnemonic::CMOVG),
            "CMOVGE" => Ok(Mnemonic::CMOVGE),
            "CMOVL" => Ok(Mnemonic::CMOVL),
            "CMOVLE" => Ok(Mnemonic::CMOVLE),
            "CMOVNA" => Ok(Mnemonic::CMOVNA),
            "CMOVNAE" => Ok(Mnemonic::CMOVNAE),
            "CMOVNB" => Ok(Mnemonic::CMOVNB),
            "CMOVNBE" => Ok(Mnemonic::CMOVNBE),
            "CMOVNC" => Ok(Mnemonic::CMOVNC),
            "CMOVNE" => Ok(Mnemonic::CMOVNE),
            "CMOVNG" => Ok(Mnemonic::CMOVNG),
            "CMOVNGE" => Ok(Mnemonic::CMOVNGE),
            "CMOVNL" => Ok(Mnemonic::CMOVNL),
            "CMOVNLE" => Ok(Mnemonic::CMOVNLE),
            "CMOVNO" => Ok(Mnemonic::CMOVNO),
            "CMOVNP" => Ok(Mnemonic::CMOVNP),
            "CMOVNS" => Ok(Mnemonic::CMOVNS),
            "CMOVNZ" => Ok(Mnemonic::CMOVNZ),
            "CMOVO" => Ok(Mnemonic::CMOVO),
            "CMOVP" => Ok(Mnemonic::CMOVP),
            "CMOVPE" => Ok(Mnemonic::CMOVPE),
            "CMP" => Ok(Mnemonic::CMP),
            "CMPPD" => Ok(Mnemonic::CMPPD),
            "CMPPS" => Ok(Mnemonic::CMPPS),
            "CMPS" => Ok(Mnemonic::CMPS),
            "CMPSB" => Ok(Mnemonic::CMPSB),
            "CMPSD" => Ok(Mnemonic::CMPSD),
            "CMPSQ" => Ok(Mnemonic::CMPSQ),
            "CMPSS" => Ok(Mnemonic::CMPSS),
            "CMPSW" => Ok(Mnemonic::CMPSW),
            "CMPXCHG" => Ok(Mnemonic::CMPXCHG),
            "CMPXCHG16B" => Ok(Mnemonic::CMPXCHG16B),
            "CMPXCHG8B" => Ok(Mnemonic::CMPXCHG8B),
            "COMISD" => Ok(Mnemonic::COMISD),
            "COMISS" => Ok(Mnemonic::COMISS),
            "CPUID" => Ok(Mnemonic::CPUID),
            "CQO" => Ok(Mnemonic::CQO),
            "CRC32" => Ok(Mnemonic::CRC32),
            "CVTDQ2PD" => Ok(Mnemonic::CVTDQ2PD),
            "CVTDQ2PS" => Ok(Mnemonic::CVTDQ2PS),
            "CVTPD2DQ" => Ok(Mnemonic::CVTPD2DQ),
            "CVTPD2PI" => Ok(Mnemonic::CVTPD2PI),
            "CVTPD2PS" => Ok(Mnemonic::CVTPD2PS),
            "CVTPI2PD" => Ok(Mnemonic::CVTPI2PD),
            "CVTPI2PS" => Ok(Mnemonic::CVTPI2PS),
            "CVTPS2DQ" => Ok(Mnemonic::CVTPS2DQ),
            "CVTPS2PD" => Ok(Mnemonic::CVTPS2PD),
            "CVTPS2PI" => Ok(Mnemonic::CVTPS2PI),
            "CVTSD2SI" => Ok(Mnemonic::CVTSD2SI),
            "CVTSD2SS" => Ok(Mnemonic::CVTSD2SS),
            "CVTSI2SD" => Ok(Mnemonic::CVTSI2SD),
            "CVTSI2SS" => Ok(Mnemonic::CVTSI2SS),
            "CVTSS2SD" => Ok(Mnemonic::CVTSS2SD),
            "CVTSS2SI" => Ok(Mnemonic::CVTSS2SI),
            "CVTTPD2DQ" => Ok(Mnemonic::CVTTPD2DQ),
            "CVTTPD2PI" => Ok(Mnemonic::CVTTPD2PI),
            "CVTTPS2DQ" => Ok(Mnemonic::CVTTPS2DQ),
            "CVTTPS2PI" => Ok(Mnemonic::CVTTPS2PI),
            "CVTTSD2SI" => Ok(Mnemonic::CVTTSD2SI),
            "CVTTSS2SI" => Ok(Mnemonic::CVTTSS2SI),
            "CWD" => Ok(Mnemonic::CWD),
            "CWDE" => Ok(Mnemonic::CWDE),
            "DAA" => Ok(Mnemonic::DAA),
            "DAS" => Ok(Mnemonic::DAS),
            "DEC" => Ok(Mnemonic::DEC),
            "DIV" => Ok(Mnemonic::DIV),
            "DIVPD" => Ok(Mnemonic::DIVPD),
            "DIVPS" => Ok(Mnemonic::DIVPS),
            "DIVSD" => Ok(Mnemonic::DIVSD),
            "DIVSS" => Ok(Mnemonic::DIVSS),
            "DPPD" => Ok(Mnemonic::DPPD),
            "DPPS" => Ok(Mnemonic::DPPS),
            "EMMS" => Ok(Mnemonic::EMMS),
            "ENTER" => Ok(Mnemonic::ENTER),
            "EXTRACTPS" => Ok(Mnemonic::EXTRACTPS),
            "F2XM1" => Ok(Mnemonic::F2XM1),
            "FABS" => Ok(Mnemonic::FABS),
            "FADD" => Ok(Mnemonic::FADD),
            "FADDP" => Ok(Mnemonic::FADDP),
            "FBLD" => Ok(Mnemonic::FBLD),
            "FBSTP" => Ok(Mnemonic::FBSTP),
            "FCHS" => Ok(Mnemonic::FCHS),
            "FCLEX" => Ok(Mnemonic::FCLEX),
            "FCMOVB" => Ok(Mnemonic::FCMOVB),
            "FCMOVBE" => Ok(Mnemonic::FCMOVBE),
            "FCMOVE" => Ok(Mnemonic::FCMOVE),
            "FCMOVNB" => Ok(Mnemonic::FCMOVNB),
            "FCMOVNBE" => Ok(Mnemonic::FCMOVNBE),
            "FCMOVNE" => Ok(Mnemonic::FCMOVNE),
            "FCMOVNU" => Ok(Mnemonic::FCMOVNU),
            "FCMOVU" => Ok(Mnemonic::FCMOVU),
            "FCOM" => Ok(Mnemonic::FCOM),
            "FCOMI" => Ok(Mnemonic::FCOMI),
            "FCOMIP" => Ok(Mnemonic::FCOMIP),
            "FCOMP" => Ok(Mnemonic::FCOMP),
            "FCOMPP" => Ok(Mnemonic::FCOMPP),
            "FCOS" => Ok(Mnemonic::FCOS),
            "FDECSTP" => Ok(Mnemonic::FDECSTP),
            "FDIV" => Ok(Mnemonic::FDIV),
            "FDIVP" => Ok(Mnemonic::FDIVP),
            "FDIVR" => Ok(Mnemonic::FDIVR),
            "FDIVRP" => Ok(Mnemonic::FDIVRP),
            "FFREE" => Ok(Mnemonic::FFREE),
            "FIADD" => Ok(Mnemonic::FIADD),
            "FICOM" => Ok(Mnemonic::FICOM),
            "FICOMP" => Ok(Mnemonic::FICOMP),
            "FIDIV" => Ok(Mnemonic::FIDIV),
            "FIDIVR" => Ok(Mnemonic::FIDIVR),
            "FILD" => Ok(Mnemonic::FILD),
            "FIMUL" => Ok(Mnemonic::FIMUL),
            "FINCSTP" => Ok(Mnemonic::FINCSTP),
            "FINIT" => Ok(Mnemonic::FINIT),
            "FIST" => Ok(Mnemonic::FIST),
            "FISTP" => Ok(Mnemonic::FISTP),
            "FISTTP" => Ok(Mnemonic::FISTTP),
            "FISUB" => Ok(Mnemonic::FISUB),
            "FISUBR" => Ok(Mnemonic::FISUBR),
            "FLD" => Ok(Mnemonic::FLD),
            "FLD1" => Ok(Mnemonic::FLD1),
            "FLDCW" => Ok(Mnemonic::FLDCW),
            "FLDENV" => Ok(Mnemonic::FLDENV),
            "FLDL2E" => Ok(Mnemonic::FLDL2E),
            "FLDL2T" => Ok(Mnemonic::FLDL2T),
            "FLDLG2" => Ok(Mnemonic::FLDLG2),
            "FLDLN2" => Ok(Mnemonic::FLDLN2),
            "FLDPI" => Ok(Mnemonic::FLDPI),
            "FLDZ" => Ok(Mnemonic::FLDZ),
            "FMUL" => Ok(Mnemonic::FMUL),
            "FMULP" => Ok(Mnemonic::FMULP),
            "FNCLEX" => Ok(Mnemonic::FNCLEX),
            "FNINIT" => Ok(Mnemonic::FNINIT),
            "FNOP" => Ok(Mnemonic::FNOP),
            "FNSAVE" => Ok(Mnemonic::FNSAVE),
            "FNSTCW" => Ok(Mnemonic::FNSTCW),
            "FNSTENV" => Ok(Mnemonic::FNSTENV),
            "FNSTSW" => Ok(Mnemonic::FNSTSW),
            "FPATAN" => Ok(Mnemonic::FPATAN),
            "FPREM" => Ok(Mnemonic::FPREM),
            "FPREM1" => Ok(Mnemonic::FPREM1),
            "FPTAN" => Ok(Mnemonic::FPTAN),
            "FRNDINT" => Ok(Mnemonic::FRNDINT),
            "FRSTOR" => Ok(Mnemonic::FRSTOR),
            "FSAVE" => Ok(Mnemonic::FSAVE),
            "FSCALE" => Ok(Mnemonic::FSCALE),
            "FSIN" => Ok(Mnemonic::FSIN),
            "FSINCOS" => Ok(Mnemonic::FSINCOS),
            "FSQRT" => Ok(Mnemonic::FSQRT),
            "FST" => Ok(Mnemonic::FST),
            "FSTCW" => Ok(Mnemonic::FSTCW),
            "FSTENV" => Ok(Mnemonic::FSTENV),
            "FSTP" => Ok(Mnemonic::FSTP),
            "FSTSW" => Ok(Mnemonic::FSTSW),
            "FSUB" => Ok(Mnemonic::FSUB),
            "FSUBP" => Ok(Mnemonic::FSUBP),
            "FSUBR" => Ok(Mnemonic::FSUBR),
            "FSUBRP" => Ok(Mnemonic::FSUBRP),
            "FTST" => Ok(Mnemonic::FTST),
            "FUCOM" => Ok(Mnemonic::FUCOM),
            "FUCOMI" => Ok(Mnemonic::FUCOMI),
            "FUCOMIP" => Ok(Mnemonic::FUCOMIP),
            "FUCOMP" => Ok(Mnemonic::FUCOMP),
            "FUCOMPP" => Ok(Mnemonic::FUCOMPP),
            "FWAIT" => Ok(Mnemonic::FWAIT),
            "FXAM" => Ok(Mnemonic::FXAM),
            "FXCH" => Ok(Mnemonic::FXCH),
            "FXRSTOR" => Ok(Mnemonic::FXRSTOR),
            "FXRSTOR64" => Ok(Mnemonic::FXRSTOR64),
            "FXSAVE" => Ok(Mnemonic::FXSAVE),
            "FXSAVE64" => Ok(Mnemonic::FXSAVE64),
            "FXTRACT" => Ok(Mnemonic::FXTRACT),
            "FYL2X" => Ok(Mnemonic::FYL2X),
            "FYL2XP1" => Ok(Mnemonic::FYL2XP1),
            "HADDPD" => Ok(Mnemonic::HADDPD),
            "HADDPS" => Ok(Mnemonic::HADDPS),
            "HLT" => Ok(Mnemonic::HLT),
            "HSUBPD" => Ok(Mnemonic::HSUBPD),
            "HSUBPS" => Ok(Mnemonic::HSUBPS),
            "IDIV" => Ok(Mnemonic::IDIV),
            "IMUL" => Ok(Mnemonic::IMUL),
            "IN" => Ok(Mnemonic::IN),
            "INC" => Ok(Mnemonic::INC),
            "INS" => Ok(Mnemonic::INS),
            "INSB" => Ok(Mnemonic::INSB),
            "INSD" => Ok(Mnemonic::INSD),
            "INSERTPS" => Ok(Mnemonic::INSERTPS),
            "INSW" => Ok(Mnemonic::INSW),
            "INT" => Ok(Mnemonic::INT),
            "INTO" => Ok(Mnemonic::INTO),
            "INVD" => Ok(Mnemonic::INVD),
            "INVLPG" => Ok(Mnemonic::INVLPG),
            "INVPCID" => Ok(Mnemonic::INVPCID),
            "IRET" => Ok(Mnemonic::IRET),
            "IRETD" => Ok(Mnemonic::IRETD),
            "IRETQ" => Ok(Mnemonic::IRETQ),
            "JA" => Ok(Mnemonic::JA),
            "JAE" => Ok(Mnemonic::JAE),
            "JB" => Ok(Mnemonic::JB),
            "JBE" => Ok(Mnemonic::JBE),
            "JC" => Ok(Mnemonic::JC),
            "JCXZ" => Ok(Mnemonic::JCXZ),
            "JE" => Ok(Mnemonic::JE),
            "JECXZ" => Ok(Mnemonic::JECXZ),
            "JG" => Ok(Mnemonic::JG),
            "JGE" => Ok(Mnemonic::JGE),
            "JL" => Ok(Mnemonic::JL),
            "JLE" => Ok(Mnemonic::JLE),
            "JMP" => Ok(Mnemonic::JMP),
            "JNA" => Ok(Mnemonic::JNA),
            "JNAE" => Ok(Mnemonic::JNAE),
            "JNB" => Ok(Mnemonic::JNB),
            "JNBE" => Ok(Mnemonic::JNBE),
            "JNC" => Ok(Mnemonic::JNC),
            "JNE" => Ok(Mnemonic::JNE),
            "JNG" => Ok(Mnemonic::JNG),
            "JNGE" => Ok(Mnemonic::JNGE),
            "JNL" => Ok(Mnemonic::JNL),
            "JNLE" => Ok(Mnemonic::JNLE),
            "JNO" => Ok(Mnemonic::JNO),
            "JNP" => Ok(Mnemonic::JNP),
            "JNS" => Ok(Mnemonic::JNS),
            "JNZ" => Ok(Mnemonic::JNZ),
            "JO" => Ok(Mnemonic::JO),
            "JP" => Ok(Mnemonic::JP),
            "JPE" => Ok(Mnemonic::JPE),
            "JPO" => Ok(Mnemonic::JPO),
            "JRCXZ" => Ok(Mnemonic::JRCXZ),
            "JS" => Ok(Mnemonic::JS),
            "JZ" => Ok(Mnemonic::JZ),
            "KADDB" => Ok(Mnemonic::KADDB),
            "KADDD" => Ok(Mnemonic::KADDD),
            "KADDQ" => Ok(Mnemonic::KADDQ),
            "KADDW" => Ok(Mnemonic::KADDW),
            "KANDB" => Ok(Mnemonic::KANDB),
            "KANDD" => Ok(Mnemonic::KANDD),
            "KANDNB" => Ok(Mnemonic::KANDNB),
            "KANDND" => Ok(Mnemonic::KANDND),
            "KANDNQ" => Ok(Mnemonic::KANDNQ),
            "KANDNW" => Ok(Mnemonic::KANDNW),
            "KANDQ" => Ok(Mnemonic::KANDQ),
            "KANDW" => Ok(Mnemonic::KANDW),
            "KMOVB" => Ok(Mnemonic::KMOVB),
            "KMOVD" => Ok(Mnemonic::KMOVD),
            "KMOVQ" => Ok(Mnemonic::KMOVQ),
            "KMOVW" => Ok(Mnemonic::KMOVW),
            "KNOTB" => Ok(Mnemonic::KNOTB),
            "KNOTD" => Ok(Mnemonic::KNOTD),
            "KNOTQ" => Ok(Mnemonic::KNOTQ),
            "KNOTW" => Ok(Mnemonic::KNOTW),
            "KORB" => Ok(Mnemonic::KORB),
            "KORD" => Ok(Mnemonic::KORD),
            "KORQ" => Ok(Mnemonic::KORQ),
            "KORTESTB" => Ok(Mnemonic::KORTESTB),
            "KORTESTD" => Ok(Mnemonic::KORTESTD),
            "KORTESTQ" => Ok(Mnemonic::KORTESTQ),
            "KORTESTW" => Ok(Mnemonic::KORTESTW),
            "KORW" => Ok(Mnemonic::KORW),
            "KSHIFTLB" => Ok(Mnemonic::KSHIFTLB),
            "KSHIFTLD" => Ok(Mnemonic::KSHIFTLD),
            "KSHIFTLQ" => Ok(Mnemonic::KSHIFTLQ),
            "KSHIFTLW" => Ok(Mnemonic::KSHIFTLW),
            "KSHIFTRB" => Ok(Mnemonic::KSHIFTRB),
            "KSHIFTRD" => Ok(Mnemonic::KSHIFTRD),
            "KSHIFTRQ" => Ok(Mnemonic::KSHIFTRQ),
            "KSHIFTRW" => Ok(Mnemonic::KSHIFTRW),
            "KTESTB" => Ok(Mnemonic::KTESTB),
            "KTESTD" => Ok(Mnemonic::KTESTD),
            "KTESTQ" => Ok(Mnemonic::KTESTQ),
            "KTESTW" => Ok(Mnemonic::KTESTW),
            "KUNPCKBW" => Ok(Mnemonic::KUNPCKBW),
            "KUNPCKDQ" => Ok(Mnemonic::KUNPCKDQ),
            "KUNPCKWD" => Ok(Mnemonic::KUNPCKWD),
            "KXNORB" => Ok(Mnemonic::KXNORB),
            "KXNORD" => Ok(Mnemonic::KXNORD),
            "KXNORQ" => Ok(Mnemonic::KXNORQ),
            "KXNORW" => Ok(Mnemonic::KXNORW),
            "KXORB" => Ok(Mnemonic::KXORB),
            "KXORD" => Ok(Mnemonic::KXORD),
            "KXORQ" => Ok(Mnemonic::KXORQ),
            "KXORW" => Ok(Mnemonic::KXORW),
            "LAHF" => Ok(Mnemonic::LAHF),
            "LAR" => Ok(Mnemonic::LAR),
            "LDDQU" => Ok(Mnemonic::LDDQU),
            "LDMXCSR" => Ok(Mnemonic::LDMXCSR),
            "LDS" => Ok(Mnemonic::LDS),
            "LEA" => Ok(Mnemonic::LEA),
            "LEAVE" => Ok(Mnemonic::LEAVE),
            "LES" => Ok(Mnemonic::LES),
            "LFENCE" => Ok(Mnemonic::LFENCE),
            "LFS" => Ok(Mnemonic::LFS),
            "LGDT" => Ok(Mnemonic::LGDT),
            "LGS" => Ok(Mnemonic::LGS),
            "LIDT" => Ok(Mnemonic::LIDT),
            "LLDT" => Ok(Mnemonic::LLDT),
            "LMSW" => Ok(Mnemonic::LMSW),
            "LOCK" => Ok(Mnemonic::LOCK),
            "LODS" => Ok(Mnemonic::LODS),
            "LODSB" => Ok(Mnemonic::LODSB),
            "LODSD" => Ok(Mnemonic::LODSD),
            "LODSQ" => Ok(Mnemonic::LODSQ),
            "LODSW" => Ok(Mnemonic::LODSW),
            "LOOP" => Ok(Mnemonic::LOOP),
            "LOOPE" => Ok(Mnemonic::LOOPE),
            "LOOPNE" => Ok(Mnemonic::LOOPNE),
            "LSL" => Ok(Mnemonic::LSL),
            "LSS" => Ok(Mnemonic::LSS),
            "LTR" => Ok(Mnemonic::LTR),
            "LZCNT" => Ok(Mnemonic::LZCNT),
            "MASKMOVDQU" => Ok(Mnemonic::MASKMOVDQU),
            "MASKMOVQ" => Ok(Mnemonic::MASKMOVQ),
            "MAXPD" => Ok(Mnemonic::MAXPD),
            "MAXPS" => Ok(Mnemonic::MAXPS),
            "MAXSD" => Ok(Mnemonic::MAXSD),
            "MAXSS" => Ok(Mnemonic::MAXSS),
            "MFENCE" => Ok(Mnemonic::MFENCE),
            "MINPD" => Ok(Mnemonic::MINPD),
            "MINPS" => Ok(Mnemonic::MINPS),
            "MINSD" => Ok(Mnemonic::MINSD),
            "MINSS" => Ok(Mnemonic::MINSS),
            "MONITOR" => Ok(Mnemonic::MONITOR),
            "MOV" => Ok(Mnemonic::MOV),
            "MOVAPD" => Ok(Mnemonic::MOVAPD),
            "MOVAPS" => Ok(Mnemonic::MOVAPS),
            "MOVBE" => Ok(Mnemonic::MOVBE),
            "MOVD" => Ok(Mnemonic::MOVD),
            "MOVDDUP" => Ok(Mnemonic::MOVDDUP),
            "MOVDQ2Q" => Ok(Mnemonic::MOVDQ2Q),
            "MOVDQA" => Ok(Mnemonic::MOVDQA),
            "MOVDQU" => Ok(Mnemonic::MOVDQU),
            "MOVHLPS" => Ok(Mnemonic::MOVHLPS),
            "MOVHPD" => Ok(Mnemonic::MOVHPD),
            "MOVHPS" => Ok(Mnemonic::MOVHPS),
            "MOVLHPS" => Ok(Mnemonic::MOVLHPS),
            "MOVLPD" => Ok(Mnemonic::MOVLPD),
            "MOVLPS" => Ok(Mnemonic::MOVLPS),
            "MOVMSKPD" => Ok(Mnemonic::MOVMSKPD),
            "MOVMSKPS" => Ok(Mnemonic::MOVMSKPS),
            "MOVNTDQ" => Ok(Mnemonic::MOVNTDQ),
            "MOVNTDQA" => Ok(Mnemonic::MOVNTDQA),
            "MOVNTI" => Ok(Mnemonic::MOVNTI),
            "MOVNTPD" => Ok(Mnemonic::MOVNTPD),
            "MOVNTPS" => Ok(Mnemonic::MOVNTPS),
            "MOVNTQ" => Ok(Mnemonic::MOVNTQ),
            "MOVQ" => Ok(Mnemonic::MOVQ),
            "MOVQ2DQ" => Ok(Mnemonic::MOVQ2DQ),
            "MOVS" => Ok(Mnemonic::MOVS),
            "MOVSB" => Ok(Mnemonic::MOVSB),
            "MOVSD" => Ok(Mnemonic::MOVSD),
            "MOVSHDUP" => Ok(Mnemonic::MOVSHDUP),
            "MOVSLDUP" => Ok(Mnemonic::MOVSLDUP),
            "MOVSQ" => Ok(Mnemonic::MOVSQ),
            "MOVSS" => Ok(Mnemonic::MOVSS),
            "MOVSW" => Ok(Mnemonic::MOVSW),
            "MOVSX" => Ok(Mnemonic::MOVSX),
            "MOVSXD" => Ok(Mnemonic::MOVSXD),
            "MOVUPD" => Ok(Mnemonic::MOVUPD),
            "MOVUPS" => Ok(Mnemonic::MOVUPS),
            "MOVZX" => Ok(Mnemonic::MOVZX),
            "MPSADBW" => Ok(Mnemonic::MPSADBW),
            "MUL" => Ok(Mnemonic::MUL),
            "MULPD" => Ok(Mnemonic::MULPD),
            "MULPS" => Ok(Mnemonic::MULPS),
            "MULSD" => Ok(Mnemonic::MULSD),
            "MULSS" => Ok(Mnemonic::MULSS),
            "MULX" => Ok(Mnemonic::MULX),
            "MWAIT" => Ok(Mnemonic::MWAIT),
            "NEG" => Ok(Mnemonic::NEG),
            "NOP" => Ok(Mnemonic::NOP),
            "NOT" => Ok(Mnemonic::NOT),
            "OR" => Ok(Mnemonic::OR),
            "ORPD" => Ok(Mnemonic::ORPD),
            "ORPS" => Ok(Mnemonic::ORPS),
            "OUT" => Ok(Mnemonic::OUT),
            "OUTS" => Ok(Mnemonic::OUTS),
            "OUTSB" => Ok(Mnemonic::OUTSB),
            "OUTSD" => Ok(Mnemonic::OUTSD),
            "OUTSW" => Ok(Mnemonic::OUTSW),
            "PABSB" => Ok(Mnemonic::PABSB),
            "PABSD" => Ok(Mnemonic::PABSD),
            "PABSW" => Ok(Mnemonic::PABSW),
            "PACKSSDW" => Ok(Mnemonic::PACKSSDW),
            "PACKSSWB" => Ok(Mnemonic::PACKSSWB),
            "PACKUSDW" => Ok(Mnemonic::PACKUSDW),
            "PACKUSWB" => Ok(Mnemonic::PACKUSWB),
            "PADDB" => Ok(Mnemonic::PADDB),
            "PADDD" => Ok(Mnemonic::PADDD),
            "PADDQ" => Ok(Mnemonic::PADDQ),
            "PADDSB" => Ok(Mnemonic::PADDSB),
            "PADDSW" => Ok(Mnemonic::PADDSW),
            "PADDUSB" => Ok(Mnemonic::PADDUSB),
            "PADDUSW" => Ok(Mnemonic::PADDUSW),
            "PADDW" => Ok(Mnemonic::PADDW),
            "PALIGNR" => Ok(Mnemonic::PALIGNR),
            "PAND" => Ok(Mnemonic::PAND),
            "PANDN" => Ok(Mnemonic::PANDN),
            "PAUSE" => Ok(Mnemonic::PAUSE),
            "PAVGB" => Ok(Mnemonic::PAVGB),
            "PAVGW" => Ok(Mnemonic::PAVGW),
            "PBLENDVB" => Ok(Mnemonic::PBLENDVB),
            "PBLENDW" => Ok(Mnemonic::PBLENDW),
            "PCLMULQDQ" => Ok(Mnemonic::PCLMULQDQ),
            "PCMPEQB" => Ok(Mnemonic::PCMPEQB),
            "PCMPEQD" => Ok(Mnemonic::PCMPEQD),
            "PCMPEQQ" => Ok(Mnemonic::PCMPEQQ),
            "PCMPEQW" => Ok(Mnemonic::PCMPEQW),
            "PCMPESTRI" => Ok(Mnemonic::PCMPESTRI),
            "PCMPESTRM" => Ok(Mnemonic::PCMPESTRM),
            "PCMPGTB" => Ok(Mnemonic::PCMPGTB),
            "PCMPGTD" => Ok(Mnemonic::PCMPGTD),
            "PCMPGTQ" => Ok(Mnemonic::PCMPGTQ),
            "PCMPGTW" => Ok(Mnemonic::PCMPGTW),
            "PCMPISTRI" => Ok(Mnemonic::PCMPISTRI),
            "PCMPISTRM" => Ok(Mnemonic::PCMPISTRM),
            "PDEP" => Ok(Mnemonic::PDEP),
            "PEXT" => Ok(Mnemonic::PEXT),
            "PEXTRB" => Ok(Mnemonic::PEXTRB),
            "PEXTRD" => Ok(Mnemonic::PEXTRD),
            "PEXTRQ" => Ok(Mnemonic::PEXTRQ),
            "PEXTRW" => Ok(Mnemonic::PEXTRW),
            "PHADDD" => Ok(Mnemonic::PHADDD),
            "PHADDSW" => Ok(Mnemonic::PHADDSW),
            "PHADDW" => Ok(Mnemonic::PHADDW),
            "PHMINPOSUW" => Ok(Mnemonic::PHMINPOSUW),
            "PHSUBD" => Ok(Mnemonic::PHSUBD),
            "PHSUBSW" => Ok(Mnemonic::PHSUBSW),
            "PHSUBW" => Ok(Mnemonic::PHSUBW),
            "PINSRB" => Ok(Mnemonic::PINSRB),
            "PINSRD" => Ok(Mnemonic::PINSRD),
            "PINSRQ" => Ok(Mnemonic::PINSRQ),
            "PINSRW" => Ok(Mnemonic::PINSRW),
            "PMADDUBSW" => Ok(Mnemonic::PMADDUBSW),
            "PMADDWD" => Ok(Mnemonic::PMADDWD),
            "PMAXSB" => Ok(Mnemonic::PMAXSB),
            "PMAXSD" => Ok(Mnemonic::PMAXSD),
            "PMAXSW" => Ok(Mnemonic::PMAXSW),
            "PMAXUB" => Ok(Mnemonic::PMAXUB),
            "PMAXUD" => Ok(Mnemonic::PMAXUD),
            "PMAXUW" => Ok(Mnemonic::PMAXUW),
            "PMINSB" => Ok(Mnemonic::PMINSB),
            "PMINSD" => Ok(Mnemonic::PMINSD),
            "PMINSW" => Ok(Mnemonic::PMINSW),
            "PMINUB" => Ok(Mnemonic::PMINUB),
            "PMINUD" => Ok(Mnemonic::PMINUD),
            "PMINUW" => Ok(Mnemonic::PMINUW),
            "PMOVMSKB" => Ok(Mnemonic::PMOVMSKB),
            "PMOVSXBD" => Ok(Mnemonic::PMOVSXBD),
            "PMOVSXBQ" => Ok(Mnemonic::PMOVSXBQ),
            "PMOVSXBW" => Ok(Mnemonic::PMOVSXBW),
            "PMOVSXDQ" => Ok(Mnemonic::PMOVSXDQ),
            "PMOVSXWD" => Ok(Mnemonic::PMOVSXWD),
            "PMOVSXWQ" => Ok(Mnemonic::PMOVSXWQ),
            "PMOVZXBD" => Ok(Mnemonic::PMOVZXBD),
            "PMOVZXBQ" => Ok(Mnemonic::PMOVZXBQ),
            "PMOVZXBW" => Ok(Mnemonic::PMOVZXBW),
            "PMOVZXDQ" => Ok(Mnemonic::PMOVZXDQ),
            "PMOVZXWD" => Ok(Mnemonic::PMOVZXWD),
            "PMOVZXWQ" => Ok(Mnemonic::PMOVZXWQ),
            "PMULDQ" => Ok(Mnemonic::PMULDQ),
            "PMULHRSW" => Ok(Mnemonic::PMULHRSW),
            "PMULHUW" => Ok(Mnemonic::PMULHUW),
            "PMULHW" => Ok(Mnemonic::PMULHW),
            "PMULLD" => Ok(Mnemonic::PMULLD),
            "PMULLW" => Ok(Mnemonic::PMULLW),
            "PMULUDQ" => Ok(Mnemonic::PMULUDQ),
            "POP" => Ok(Mnemonic::POP),
            "POPA" => Ok(Mnemonic::POPA),
            "POPAD" => Ok(Mnemonic::POPAD),
            "POPCNT" => Ok(Mnemonic::POPCNT),
            "POPF" => Ok(Mnemonic::POPF),
            "POPFD" => Ok(Mnemonic::POPFD),
            "POPFQ" => Ok(Mnemonic::POPFQ),
            "POR" => Ok(Mnemonic::POR),
            "PREFETCHNTA" => Ok(Mnemonic::PREFETCHNTA),
            "PREFETCHT0" => Ok(Mnemonic::PREFETCHT0),
            "PREFETCHT1" => Ok(Mnemonic::PREFETCHT1),
            "PREFETCHT2" => Ok(Mnemonic::PREFETCHT2),
            "PREFETCHW" => Ok(Mnemonic::PREFETCHW),
            "PREFETCHWT1" => Ok(Mnemonic::PREFETCHWT1),
            "PSADBW" => Ok(Mnemonic::PSADBW),
            "PSHUFB" => Ok(Mnemonic::PSHUFB),
            "PSHUFD" => Ok(Mnemonic::PSHUFD),
            "PSHUFHW" => Ok(Mnemonic::PSHUFHW),
            "PSHUFLW" => Ok(Mnemonic::PSHUFLW),
            "PSHUFW" => Ok(Mnemonic::PSHUFW),
            "PSIGNB" => Ok(Mnemonic::PSIGNB),
            "PSIGND" => Ok(Mnemonic::PSIGND),
            "PSIGNW" => Ok(Mnemonic::PSIGNW),
            "PSLLD" => Ok(Mnemonic::PSLLD),
            "PSLLDQ" => Ok(Mnemonic::PSLLDQ),
            "PSLLQ" => Ok(Mnemonic::PSLLQ),
            "PSLLW" => Ok(Mnemonic::PSLLW),
            "PSRAD" => Ok(Mnemonic::PSRAD),
            "PSRAW" => Ok(Mnemonic::PSRAW),
            "PSRLD" => Ok(Mnemonic::PSRLD),
            "PSRLDQ" => Ok(Mnemonic::PSRLDQ),
            "PSRLQ" => Ok(Mnemonic::PSRLQ),
            "PSRLW" => Ok(Mnemonic::PSRLW),
            "PSUBB" => Ok(Mnemonic::PSUBB),
            "PSUBD" => Ok(Mnemonic::PSUBD),
            "PSUBQ" => Ok(Mnemonic::PSUBQ),
            "PSUBSB" => Ok(Mnemonic::PSUBSB),
            "PSUBSW" => Ok(Mnemonic::PSUBSW),
            "PSUBUSB" => Ok(Mnemonic::PSUBUSB),
            "PSUBUSW" => Ok(Mnemonic::PSUBUSW),
            "PSUBW" => Ok(Mnemonic::PSUBW),
            "PTEST" => Ok(Mnemonic::PTEST),
            "PTWRITE" => Ok(Mnemonic::PTWRITE),
            "PUNPCKHBW" => Ok(Mnemonic::PUNPCKHBW),
            "PUNPCKHDQ" => Ok(Mnemonic::PUNPCKHDQ),
            "PUNPCKHQDQ" => Ok(Mnemonic::PUNPCKHQDQ),
            "PUNPCKHWD" => Ok(Mnemonic::PUNPCKHWD),
            "PUNPCKLBW" => Ok(Mnemonic::PUNPCKLBW),
            "PUNPCKLDQ" => Ok(Mnemonic::PUNPCKLDQ),
            "PUNPCKLQDQ" => Ok(Mnemonic::PUNPCKLQDQ),
            "PUNPCKLWD" => Ok(Mnemonic::PUNPCKLWD),
            "PUSH" => Ok(Mnemonic::PUSH),
            "PUSHA" => Ok(Mnemonic::PUSHA),
            "PUSHAD" => Ok(Mnemonic::PUSHAD),
            "PUSHF" => Ok(Mnemonic::PUSHF),
            "PUSHFD" => Ok(Mnemonic::PUSHFD),
            "PUSHFQ" => Ok(Mnemonic::PUSHFQ),
            "PXOR" => Ok(Mnemonic::PXOR),
            "RCL" => Ok(Mnemonic::RCL),
            "RCPPS" => Ok(Mnemonic::RCPPS),
            "RCPSS" => Ok(Mnemonic::RCPSS),
            "RCR" => Ok(Mnemonic::RCR),
            "RDFSBASE" => Ok(Mnemonic::RDFSBASE),
            "RDGSBASE" => Ok(Mnemonic::RDGSBASE),
            "RDMSR" => Ok(Mnemonic::RDMSR),
            "RDPID" => Ok(Mnemonic::RDPID),
            "RDPKRU" => Ok(Mnemonic::RDPKRU),
            "RDPMC" => Ok(Mnemonic::RDPMC),
            "RDRAND" => Ok(Mnemonic::RDRAND),
            "RDSEED" => Ok(Mnemonic::RDSEED),
            "RDTSC" => Ok(Mnemonic::RDTSC),
            "RDTSCP" => Ok(Mnemonic::RDTSCP),
            "RET" => Ok(Mnemonic::RET),
            "ROL" => Ok(Mnemonic::ROL),
            "ROR" => Ok(Mnemonic::ROR),
            "RORX" => Ok(Mnemonic::RORX),
            "ROUNDPD" => Ok(Mnemonic::ROUNDPD),
            "ROUNDPS" => Ok(Mnemonic::ROUNDPS),
            "ROUNDSD" => Ok(Mnemonic::ROUNDSD),
            "ROUNDSS" => Ok(Mnemonic::ROUNDSS),
            "RSM" => Ok(Mnemonic::RSM),
            "RSQRTPS" => Ok(Mnemonic::RSQRTPS),
            "RSQRTSS" => Ok(Mnemonic::RSQRTSS),
            "SAHF" => Ok(Mnemonic::SAHF),
            "SAL" => Ok(Mnemonic::SAL),
            "SAR" => Ok(Mnemonic::SAR),
            "SARX" => Ok(Mnemonic::SARX),
            "SBB" => Ok(Mnemonic::SBB),
            "SCAS" => Ok(Mnemonic::SCAS),
            "SCASB" => Ok(Mnemonic::SCASB),
            "SCASD" => Ok(Mnemonic::SCASD),
            "SCASQ" => Ok(Mnemonic::SCASQ),
            "SCASW" => Ok(Mnemonic::SCASW),
            "SETA" => Ok(Mnemonic::SETA),
            "SETAE" => Ok(Mnemonic::SETAE),
            "SETB" => Ok(Mnemonic::SETB),
            "SETBE" => Ok(Mnemonic::SETBE),
            "SETC" => Ok(Mnemonic::SETC),
            "SETE" => Ok(Mnemonic::SETE),
            "SETG" => Ok(Mnemonic::SETG),
            "SETGE" => Ok(Mnemonic::SETGE),
            "SETL" => Ok(Mnemonic::SETL),
            "SETLE" => Ok(Mnemonic::SETLE),
            "SETNA" => Ok(Mnemonic::SETNA),
            "SETNAE" => Ok(Mnemonic::SETNAE),
            "SETNB" => Ok(Mnemonic::SETNB),
            "SETNBE" => Ok(Mnemonic::SETNBE),
            "SETNC" => Ok(Mnemonic::SETNC),
            "SETNE" => Ok(Mnemonic::SETNE),
            "SETNG" => Ok(Mnemonic::SETNG),
            "SETNGE" => Ok(Mnemonic::SETNGE),
            "SETNL" => Ok(Mnemonic::SETNL),
            "SETNLE" => Ok(Mnemonic::SETNLE),
            "SFENCE" => Ok(Mnemonic::SFENCE),
            "SGDT" => Ok(Mnemonic::SGDT),
            "SHA1MSG1" => Ok(Mnemonic::SHA1MSG1),
            "SHA1MSG2" => Ok(Mnemonic::SHA1MSG2),
            "SHA1NEXTE" => Ok(Mnemonic::SHA1NEXTE),
            "SHA1RNDS4" => Ok(Mnemonic::SHA1RNDS4),
            "SHA256MSG1" => Ok(Mnemonic::SHA256MSG1),
            "SHA256MSG2" => Ok(Mnemonic::SHA256MSG2),
            "SHA256RNDS2" => Ok(Mnemonic::SHA256RNDS2),
            "SHL" => Ok(Mnemonic::SHL),
            "SHLD" => Ok(Mnemonic::SHLD),
            "SHLX" => Ok(Mnemonic::SHLX),
            "SHR" => Ok(Mnemonic::SHR),
            "SHRD" => Ok(Mnemonic::SHRD),
            "SHRX" => Ok(Mnemonic::SHRX),
            "SHUFPD" => Ok(Mnemonic::SHUFPD),
            "SHUFPS" => Ok(Mnemonic::SHUFPS),
            "SIDT" => Ok(Mnemonic::SIDT),
            "SLDT" => Ok(Mnemonic::SLDT),
            "SMSW" => Ok(Mnemonic::SMSW),
            "SQRTPD" => Ok(Mnemonic::SQRTPD),
            "SQRTPS" => Ok(Mnemonic::SQRTPS),
            "SQRTSD" => Ok(Mnemonic::SQRTSD),
            "SQRTSS" => Ok(Mnemonic::SQRTSS),
            "STAC" => Ok(Mnemonic::STAC),
            "STC" => Ok(Mnemonic::STC),
            "STD" => Ok(Mnemonic::STD),
            "STI" => Ok(Mnemonic::STI),
            "STMXCSR" => Ok(Mnemonic::STMXCSR),
            "STOS" => Ok(Mnemonic::STOS),
            "STOSB" => Ok(Mnemonic::STOSB),
            "STOSD" => Ok(Mnemonic::STOSD),
            "STOSQ" => Ok(Mnemonic::STOSQ),
            "STOSW" => Ok(Mnemonic::STOSW),
            "STR" => Ok(Mnemonic::STR),
            "SUB" => Ok(Mnemonic::SUB),
            "SUBPD" => Ok(Mnemonic::SUBPD),
            "SUBPS" => Ok(Mnemonic::SUBPS),
            "SUBSD" => Ok(Mnemonic::SUBSD),
            "SUBSS" => Ok(Mnemonic::SUBSS),
            "SWAPGS" => Ok(Mnemonic::SWAPGS),
            "SYSCALL" => Ok(Mnemonic::SYSCALL),
            "SYSENTER" => Ok(Mnemonic::SYSENTER),
            "SYSEXIT" => Ok(Mnemonic::SYSEXIT),
            "SYSRET" => Ok(Mnemonic::SYSRET),
            "TEST" => Ok(Mnemonic::TEST),
            "TZCNT" => Ok(Mnemonic::TZCNT),
            "UCOMISD" => Ok(Mnemonic::UCOMISD),
            "UCOMISS" => Ok(Mnemonic::UCOMISS),
            "UD0" => Ok(Mnemonic::UD0),
            "UD1" => Ok(Mnemonic::UD1),
            "UD2" => Ok(Mnemonic::UD2),
            "UNPCKHPD" => Ok(Mnemonic::UNPCKHPD),
            "UNPCKHPS" => Ok(Mnemonic::UNPCKHPS),
            "UNPCKLPD" => Ok(Mnemonic::UNPCKLPD),
            "UNPCKLPS" => Ok(Mnemonic::UNPCKLPS),
            "VADDPD" => Ok(Mnemonic::VADDPD),
            "VADDPS" => Ok(Mnemonic::VADDPS),
            "VADDSD" => Ok(Mnemonic::VADDSD),
            "VADDSS" => Ok(Mnemonic::VADDSS),
            "VADDSUBPD" => Ok(Mnemonic::VADDSUBPD),
            "VADDSUBPS" => Ok(Mnemonic::VADDSUBPS),
            "VAESDEC" => Ok(Mnemonic::VAESDEC),
            "VAESDECLAST" => Ok(Mnemonic::VAESDECLAST),
            "VAESENC" => Ok(Mnemonic::VAESENC),
            "VAESENCLAST" => Ok(Mnemonic::VAESENCLAST),
            "VAESIMC" => Ok(Mnemonic::VAESIMC),
            "VAESKEYGENASSIST" => Ok(Mnemonic::VAESKEYGENASSIST),
            "VALIGND" => Ok(Mnemonic::VALIGND),
            "VALIGNQ" => Ok(Mnemonic::VALIGNQ),
            "VANDNPD" => Ok(Mnemonic::VANDNPD),
            "VANDNPS" => Ok(Mnemonic::VANDNPS),
            "VANDPD" => Ok(Mnemonic::VANDPD),
            "VANDPS" => Ok(Mnemonic::VANDPS),
            "VBLENDMPD" => Ok(Mnemonic::VBLENDMPD),
            "VBLENDMPS" => Ok(Mnemonic::VBLENDMPS),
            "VBLENDPD" => Ok(Mnemonic::VBLENDPD),
            "VBLENDPS" => Ok(Mnemonic::VBLENDPS),
            "VBLENDVPD" => Ok(Mnemonic::VBLENDVPD),
            "VBLENDVPS" => Ok(Mnemonic::VBLENDVPS),
            "VBROADCASTF128" => Ok(Mnemonic::VBROADCASTF128),
            "VBROADCASTF32X2" => Ok(Mnemonic::VBROADCASTF32X2),
            "VBROADCASTF32X4" => Ok(Mnemonic::VBROADCASTF32X4),
            "VBROADCASTF64X2" => Ok(Mnemonic::VBROADCASTF64X2),
            "VBROADCASTI128" => Ok(Mnemonic::VBROADCASTI128),
            "VBROADCASTI32x2" => Ok(Mnemonic::VBROADCASTI32x2),
            "VBROADCASTI32X4" => Ok(Mnemonic::VBROADCASTI32X4),
            "VBROADCASTI32X8" => Ok(Mnemonic::VBROADCASTI32X8),
            "VBROADCASTI64X2" => Ok(Mnemonic::VBROADCASTI64X2),
            "VBROADCASTI64X4" => Ok(Mnemonic::VBROADCASTI64X4),
            "VBROADCASTSD" => Ok(Mnemonic::VBROADCASTSD),
            "VBROADCASTSS" => Ok(Mnemonic::VBROADCASTSS),
            "VCMPPD" => Ok(Mnemonic::VCMPPD),
            "VCMPPS" => Ok(Mnemonic::VCMPPS),
            "VCMPSD" => Ok(Mnemonic::VCMPSD),
            "VCMPSS" => Ok(Mnemonic::VCMPSS),
            "VCOMISD" => Ok(Mnemonic::VCOMISD),
            "VCOMISS" => Ok(Mnemonic::VCOMISS),
            "VCOMPRESSPD" => Ok(Mnemonic::VCOMPRESSPD),
            "VCOMPRESSPS" => Ok(Mnemonic::VCOMPRESSPS),
            "VCVTDQ2PD" => Ok(Mnemonic::VCVTDQ2PD),
            "VCVTDQ2PS" => Ok(Mnemonic::VCVTDQ2PS),
            "VCVTPD2DQ" => Ok(Mnemonic::VCVTPD2DQ),
            "VCVTPD2PS" => Ok(Mnemonic::VCVTPD2PS),
            "VCVTPD2QQ" => Ok(Mnemonic::VCVTPD2QQ),
            "VCVTPD2UDQ" => Ok(Mnemonic::VCVTPD2UDQ),
            "VCVTPD2UQQ" => Ok(Mnemonic::VCVTPD2UQQ),
            "VCVTPH2PS" => Ok(Mnemonic::VCVTPH2PS),
            "VCVTPS2DQ" => Ok(Mnemonic::VCVTPS2DQ),
            "VCVTPS2PD" => Ok(Mnemonic::VCVTPS2PD),
            "VCVTPS2PH" => Ok(Mnemonic::VCVTPS2PH),
            "VCVTPS2QQ" => Ok(Mnemonic::VCVTPS2QQ),
            "VCVTPS2UDQ" => Ok(Mnemonic::VCVTPS2UDQ),
            "VCVTPS2UQQ" => Ok(Mnemonic::VCVTPS2UQQ),
            "VCVTQQ2PD" => Ok(Mnemonic::VCVTQQ2PD),
            "VCVTQQ2PS" => Ok(Mnemonic::VCVTQQ2PS),
            "VCVTSD2SI" => Ok(Mnemonic::VCVTSD2SI),
            "VCVTSD2SS" => Ok(Mnemonic::VCVTSD2SS),
            "VCVTSD2USI" => Ok(Mnemonic::VCVTSD2USI),
            "VCVTSI2SD" => Ok(Mnemonic::VCVTSI2SD),
            "VCVTSI2SS" => Ok(Mnemonic::VCVTSI2SS),
            "VCVTSS2SD" => Ok(Mnemonic::VCVTSS2SD),
            "VCVTSS2SI" => Ok(Mnemonic::VCVTSS2SI),
            "VCVTSS2USI" => Ok(Mnemonic::VCVTSS2USI),
            "VCVTTPD2DQ" => Ok(Mnemonic::VCVTTPD2DQ),
            "VCVTTPD2QQ" => Ok(Mnemonic::VCVTTPD2QQ),
            "VCVTTPD2UDQ" => Ok(Mnemonic::VCVTTPD2UDQ),
            "VCVTTPD2UQQ" => Ok(Mnemonic::VCVTTPD2UQQ),
            "VCVTTPS2DQ" => Ok(Mnemonic::VCVTTPS2DQ),
            "VCVTTPS2QQ" => Ok(Mnemonic::VCVTTPS2QQ),
            "VCVTTPS2UDQ" => Ok(Mnemonic::VCVTTPS2UDQ),
            "VCVTTPS2UQQ" => Ok(Mnemonic::VCVTTPS2UQQ),
            "VCVTTSD2SI" => Ok(Mnemonic::VCVTTSD2SI),
            "VCVTTSD2USI" => Ok(Mnemonic::VCVTTSD2USI),
            "VCVTTSS2SI" => Ok(Mnemonic::VCVTTSS2SI),
            "VCVTTSS2USI" => Ok(Mnemonic::VCVTTSS2USI),
            "VCVTUDQ2PD" => Ok(Mnemonic::VCVTUDQ2PD),
            "VCVTUDQ2PS" => Ok(Mnemonic::VCVTUDQ2PS),
            "VCVTUQQ2PD" => Ok(Mnemonic::VCVTUQQ2PD),
            "VCVTUQQ2PS" => Ok(Mnemonic::VCVTUQQ2PS),
            "VCVTUSI2SD" => Ok(Mnemonic::VCVTUSI2SD),
            "VCVTUSI2SS" => Ok(Mnemonic::VCVTUSI2SS),
            "VDBPSADBW" => Ok(Mnemonic::VDBPSADBW),
            "VDIVPD" => Ok(Mnemonic::VDIVPD),
            "VDIVPS" => Ok(Mnemonic::VDIVPS),
            "VDIVSD" => Ok(Mnemonic::VDIVSD),
            "VDIVSS" => Ok(Mnemonic::VDIVSS),
            "VDPPD" => Ok(Mnemonic::VDPPD),
            "VDPPS" => Ok(Mnemonic::VDPPS),
            "VERR" => Ok(Mnemonic::VERR),
            "VERW" => Ok(Mnemonic::VERW),
            "VEXP2PD" => Ok(Mnemonic::VEXP2PD),
            "VEXP2PS" => Ok(Mnemonic::VEXP2PS),
            "VEXPANDPD" => Ok(Mnemonic::VEXPANDPD),
            "VEXPANDPS" => Ok(Mnemonic::VEXPANDPS),
            "VEXTRACTF128" => Ok(Mnemonic::VEXTRACTF128),
            "VEXTRACTF32x4" => Ok(Mnemonic::VEXTRACTF32x4),
            "VEXTRACTF64x4" => Ok(Mnemonic::VEXTRACTF64x4),
            "VEXTRACTI128" => Ok(Mnemonic::VEXTRACTI128),
            "VEXTRACTI32x4" => Ok(Mnemonic::VEXTRACTI32x4),
            "VEXTRACTI64x4" => Ok(Mnemonic::VEXTRACTI64x4),
            "VEXTRACTPS" => Ok(Mnemonic::VEXTRACTPS),
            "VFIXUPIMMPD" => Ok(Mnemonic::VFIXUPIMMPD),
            "VFIXUPIMMPS" => Ok(Mnemonic::VFIXUPIMMPS),
            "VFIXUPIMMSD" => Ok(Mnemonic::VFIXUPIMMSD),
            "VFIXUPIMMSS" => Ok(Mnemonic::VFIXUPIMMSS),
            "VFMADD132PD" => Ok(Mnemonic::VFMADD132PD),
            "VFMADD132PS" => Ok(Mnemonic::VFMADD132PS),
            "VFMADD132SD" => Ok(Mnemonic::VFMADD132SD),
            "VFMADD132SS" => Ok(Mnemonic::VFMADD132SS),
            "VFMADD213PD" => Ok(Mnemonic::VFMADD213PD),
            "VFMADD213PS" => Ok(Mnemonic::VFMADD213PS),
            "VFMADD213SD" => Ok(Mnemonic::VFMADD213SD),
            "VFMADD213SS" => Ok(Mnemonic::VFMADD213SS),
            "VFMADD231PD" => Ok(Mnemonic::VFMADD231PD),
            "VFMADD231PS" => Ok(Mnemonic::VFMADD231PS),
            "VFMADD231SD" => Ok(Mnemonic::VFMADD231SD),
            "VFMADD231SS" => Ok(Mnemonic::VFMADD231SS),
            "VFMADDSUB132PD" => Ok(Mnemonic::VFMADDSUB132PD),
            "VFMADDSUB132PS" => Ok(Mnemonic::VFMADDSUB132PS),
            "VFMADDSUB213PD" => Ok(Mnemonic::VFMADDSUB213PD),
            "VFMADDSUB213PS" => Ok(Mnemonic::VFMADDSUB213PS),
            "VFMADDSUB231PD" => Ok(Mnemonic::VFMADDSUB231PD),
            "VFMADDSUB231PS" => Ok(Mnemonic::VFMADDSUB231PS),
            "VFMSUB132PD" => Ok(Mnemonic::VFMSUB132PD),
            "VFMSUB132PS" => Ok(Mnemonic::VFMSUB132PS),
            "VFMSUB132SD" => Ok(Mnemonic::VFMSUB132SD),
            "VFMSUB132SS" => Ok(Mnemonic::VFMSUB132SS),
            "VFMSUB213PD" => Ok(Mnemonic::VFMSUB213PD),
            "VFMSUB213PS" => Ok(Mnemonic::VFMSUB213PS),
            "VFMSUB213SD" => Ok(Mnemonic::VFMSUB213SD),
            "VFMSUB213SS" => Ok(Mnemonic::VFMSUB213SS),
            "VFMSUB231PD" => Ok(Mnemonic::VFMSUB231PD),
            "VFMSUB231PS" => Ok(Mnemonic::VFMSUB231PS),
            "VFMSUB231SD" => Ok(Mnemonic::VFMSUB231SD),
            "VFMSUB231SS" => Ok(Mnemonic::VFMSUB231SS),
            "VFMSUBADD132PD" => Ok(Mnemonic::VFMSUBADD132PD),
            "VFMSUBADD132PS" => Ok(Mnemonic::VFMSUBADD132PS),
            "VFMSUBADD213PD" => Ok(Mnemonic::VFMSUBADD213PD),
            "VFMSUBADD213PS" => Ok(Mnemonic::VFMSUBADD213PS),
            "VFMSUBADD231PD" => Ok(Mnemonic::VFMSUBADD231PD),
            "VFMSUBADD231PS" => Ok(Mnemonic::VFMSUBADD231PS),
            "VFNMADD132PD" => Ok(Mnemonic::VFNMADD132PD),
            "VFNMADD132PS" => Ok(Mnemonic::VFNMADD132PS),
            "VFNMADD132SD" => Ok(Mnemonic::VFNMADD132SD),
            "VFNMADD132SS" => Ok(Mnemonic::VFNMADD132SS),
            "VFNMADD213PD" => Ok(Mnemonic::VFNMADD213PD),
            "VFNMADD213PS" => Ok(Mnemonic::VFNMADD213PS),
            "VFNMADD213SD" => Ok(Mnemonic::VFNMADD213SD),
            "VFNMADD213SS" => Ok(Mnemonic::VFNMADD213SS),
            "VFNMADD231PD" => Ok(Mnemonic::VFNMADD231PD),
            "VFNMADD231PS" => Ok(Mnemonic::VFNMADD231PS),
            "VFNMADD231SD" => Ok(Mnemonic::VFNMADD231SD),
            "VFNMADD231SS" => Ok(Mnemonic::VFNMADD231SS),
            "VFNMSUB132PD" => Ok(Mnemonic::VFNMSUB132PD),
            "VFNMSUB132PS" => Ok(Mnemonic::VFNMSUB132PS),
            "VFNMSUB132SD" => Ok(Mnemonic::VFNMSUB132SD),
            "VFNMSUB132SS" => Ok(Mnemonic::VFNMSUB132SS),
            "VFNMSUB213PD" => Ok(Mnemonic::VFNMSUB213PD),
            "VFNMSUB213PS" => Ok(Mnemonic::VFNMSUB213PS),
            "VFNMSUB213SD" => Ok(Mnemonic::VFNMSUB213SD),
            "VFNMSUB213SS" => Ok(Mnemonic::VFNMSUB213SS),
            "VFNMSUB231PD" => Ok(Mnemonic::VFNMSUB231PD),
            "VFNMSUB231PS" => Ok(Mnemonic::VFNMSUB231PS),
            "VFNMSUB231SD" => Ok(Mnemonic::VFNMSUB231SD),
            "VFNMSUB231SS" => Ok(Mnemonic::VFNMSUB231SS),
            "VFPCLASSPD" => Ok(Mnemonic::VFPCLASSPD),
            "VFPCLASSPS" => Ok(Mnemonic::VFPCLASSPS),
            "VFPCLASSSD" => Ok(Mnemonic::VFPCLASSSD),
            "VFPCLASSSS" => Ok(Mnemonic::VFPCLASSSS),
            "VGATHERDPD" => Ok(Mnemonic::VGATHERDPD),
            "VGATHERDPS" => Ok(Mnemonic::VGATHERDPS),
            "VGATHERPF0DPD" => Ok(Mnemonic::VGATHERPF0DPD),
            "VGATHERPF0DPS" => Ok(Mnemonic::VGATHERPF0DPS),
            "VGATHERPF0QPD" => Ok(Mnemonic::VGATHERPF0QPD),
            "VGATHERPF0QPS" => Ok(Mnemonic::VGATHERPF0QPS),
            "VGATHERPF1DPD" => Ok(Mnemonic::VGATHERPF1DPD),
            "VGATHERPF1DPS" => Ok(Mnemonic::VGATHERPF1DPS),
            "VGATHERPF1QPD" => Ok(Mnemonic::VGATHERPF1QPD),
            "VGATHERPF1QPS" => Ok(Mnemonic::VGATHERPF1QPS),
            "VGATHERQPD" => Ok(Mnemonic::VGATHERQPD),
            "VGATHERQPS" => Ok(Mnemonic::VGATHERQPS),
            "VGETEXPPD" => Ok(Mnemonic::VGETEXPPD),
            "VGETEXPPS" => Ok(Mnemonic::VGETEXPPS),
            "VGETEXPSD" => Ok(Mnemonic::VGETEXPSD),
            "VGETEXPSS" => Ok(Mnemonic::VGETEXPSS),
            "VGETMANTPD" => Ok(Mnemonic::VGETMANTPD),
            "VGETMANTPS" => Ok(Mnemonic::VGETMANTPS),
            "VGETMANTSD" => Ok(Mnemonic::VGETMANTSD),
            "VGETMANTSS" => Ok(Mnemonic::VGETMANTSS),
            "VHADDPD" => Ok(Mnemonic::VHADDPD),
            "VHADDPS" => Ok(Mnemonic::VHADDPS),
            "VHSUBPD" => Ok(Mnemonic::VHSUBPD),
            "VHSUBPS" => Ok(Mnemonic::VHSUBPS),
            "VINSERTF128" => Ok(Mnemonic::VINSERTF128),
            "VINSERTI128" => Ok(Mnemonic::VINSERTI128),
            "VINSERTPS" => Ok(Mnemonic::VINSERTPS),
            "VLDDQU" => Ok(Mnemonic::VLDDQU),
            "VLDMXCSR" => Ok(Mnemonic::VLDMXCSR),
            "VMASKMOVDQU" => Ok(Mnemonic::VMASKMOVDQU),
            "VMASKMOVPD" => Ok(Mnemonic::VMASKMOVPD),
            "VMASKMOVPS" => Ok(Mnemonic::VMASKMOVPS),
            "VMAXPD" => Ok(Mnemonic::VMAXPD),
            "VMAXPS" => Ok(Mnemonic::VMAXPS),
            "VMAXSD" => Ok(Mnemonic::VMAXSD),
            "VMAXSS" => Ok(Mnemonic::VMAXSS),
            "VMINPD" => Ok(Mnemonic::VMINPD),
            "VMINPS" => Ok(Mnemonic::VMINPS),
            "VMINSD" => Ok(Mnemonic::VMINSD),
            "VMINSS" => Ok(Mnemonic::VMINSS),
            "VMOVAPD" => Ok(Mnemonic::VMOVAPD),
            "VMOVAPS" => Ok(Mnemonic::VMOVAPS),
            "VMOVD" => Ok(Mnemonic::VMOVD),
            "VMOVDDUP" => Ok(Mnemonic::VMOVDDUP),
            "VMOVDQA" => Ok(Mnemonic::VMOVDQA),
            "VMOVDQA32" => Ok(Mnemonic::VMOVDQA32),
            "VMOVDQA64" => Ok(Mnemonic::VMOVDQA64),
            "VMOVDQU" => Ok(Mnemonic::VMOVDQU),
            "VMOVDQU16" => Ok(Mnemonic::VMOVDQU16),
            "VMOVDQU32" => Ok(Mnemonic::VMOVDQU32),
            "VMOVDQU64" => Ok(Mnemonic::VMOVDQU64),
            "VMOVDQU8" => Ok(Mnemonic::VMOVDQU8),
            "VMOVHLPS" => Ok(Mnemonic::VMOVHLPS),
            "VMOVHPD" => Ok(Mnemonic::VMOVHPD),
            "VMOVHPS" => Ok(Mnemonic::VMOVHPS),
            "VMOVLHPS" => Ok(Mnemonic::VMOVLHPS),
            "VMOVLPD" => Ok(Mnemonic::VMOVLPD),
            "VMOVLPS" => Ok(Mnemonic::VMOVLPS),
            "VMOVMSKPD" => Ok(Mnemonic::VMOVMSKPD),
            "VMOVMSKPS" => Ok(Mnemonic::VMOVMSKPS),
            "VMOVNTDQ" => Ok(Mnemonic::VMOVNTDQ),
            "VMOVNTDQA" => Ok(Mnemonic::VMOVNTDQA),
            "VMOVNTPD" => Ok(Mnemonic::VMOVNTPD),
            "VMOVNTPS" => Ok(Mnemonic::VMOVNTPS),
            "VMOVQ" => Ok(Mnemonic::VMOVQ),
            "VMOVSD" => Ok(Mnemonic::VMOVSD),
            "VMOVSHDUP" => Ok(Mnemonic::VMOVSHDUP),
            "VMOVSLDUP" => Ok(Mnemonic::VMOVSLDUP),
            "VMOVSS" => Ok(Mnemonic::VMOVSS),
            "VMOVUPD" => Ok(Mnemonic::VMOVUPD),
            "VMOVUPS" => Ok(Mnemonic::VMOVUPS),
            "VMPSADBW" => Ok(Mnemonic::VMPSADBW),
            "VMULPD" => Ok(Mnemonic::VMULPD),
            "VMULPS" => Ok(Mnemonic::VMULPS),
            "VMULSD" => Ok(Mnemonic::VMULSD),
            "VMULSS" => Ok(Mnemonic::VMULSS),
            "VORPD" => Ok(Mnemonic::VORPD),
            "VORPS" => Ok(Mnemonic::VORPS),
            "VPABSB" => Ok(Mnemonic::VPABSB),
            "VPABSD" => Ok(Mnemonic::VPABSD),
            "VPABSW" => Ok(Mnemonic::VPABSW),
            "VPACKSSDW" => Ok(Mnemonic::VPACKSSDW),
            "VPACKSSWB" => Ok(Mnemonic::VPACKSSWB),
            "VPACKUSDW" => Ok(Mnemonic::VPACKUSDW),
            "VPACKUSWB" => Ok(Mnemonic::VPACKUSWB),
            "VPADDB" => Ok(Mnemonic::VPADDB),
            "VPADDD" => Ok(Mnemonic::VPADDD),
            "VPADDQ" => Ok(Mnemonic::VPADDQ),
            "VPADDSB" => Ok(Mnemonic::VPADDSB),
            "VPADDSW" => Ok(Mnemonic::VPADDSW),
            "VPADDUSB" => Ok(Mnemonic::VPADDUSB),
            "VPADDUSW" => Ok(Mnemonic::VPADDUSW),
            "VPADDW" => Ok(Mnemonic::VPADDW),
            "VPALIGNR" => Ok(Mnemonic::VPALIGNR),
            "VPAND" => Ok(Mnemonic::VPAND),
            "VPANDD" => Ok(Mnemonic::VPANDD),
            "VPANDN" => Ok(Mnemonic::VPANDN),
            "VPANDND" => Ok(Mnemonic::VPANDND),
            "VPANDNQ" => Ok(Mnemonic::VPANDNQ),
            "VPANDQ" => Ok(Mnemonic::VPANDQ),
            "VPAVGB" => Ok(Mnemonic::VPAVGB),
            "VPAVGW" => Ok(Mnemonic::VPAVGW),
            "VPBLENDD" => Ok(Mnemonic::VPBLENDD),
            "VPBLENDMB" => Ok(Mnemonic::VPBLENDMB),
            "VPBLENDMD" => Ok(Mnemonic::VPBLENDMD),
            "VPBLENDMQ" => Ok(Mnemonic::VPBLENDMQ),
            "VPBLENDMW" => Ok(Mnemonic::VPBLENDMW),
            "VPBLENDVB" => Ok(Mnemonic::VPBLENDVB),
            "VPBLENDW" => Ok(Mnemonic::VPBLENDW),
            "VPBROADCASTB" => Ok(Mnemonic::VPBROADCASTB),
            "VPBROADCASTD" => Ok(Mnemonic::VPBROADCASTD),
            "VPBROADCASTMB2Q" => Ok(Mnemonic::VPBROADCASTMB2Q),
            "VPBROADCASTMW2D" => Ok(Mnemonic::VPBROADCASTMW2D),
            "VPBROADCASTQ" => Ok(Mnemonic::VPBROADCASTQ),
            "VPBROADCASTW" => Ok(Mnemonic::VPBROADCASTW),
            "VPCLMULQDQ" => Ok(Mnemonic::VPCLMULQDQ),
            "VPCMPB" => Ok(Mnemonic::VPCMPB),
            "VPCMPD" => Ok(Mnemonic::VPCMPD),
            "VPCMPEQB" => Ok(Mnemonic::VPCMPEQB),
            "VPCMPEQD" => Ok(Mnemonic::VPCMPEQD),
            "VPCMPEQQ" => Ok(Mnemonic::VPCMPEQQ),
            "VPCMPEQW" => Ok(Mnemonic::VPCMPEQW),
            "VPCMPESTRI" => Ok(Mnemonic::VPCMPESTRI),
            "VPCMPESTRM" => Ok(Mnemonic::VPCMPESTRM),
            "VPCMPGTB" => Ok(Mnemonic::VPCMPGTB),
            "VPCMPGTD" => Ok(Mnemonic::VPCMPGTD),
            "VPCMPGTQ" => Ok(Mnemonic::VPCMPGTQ),
            "VPCMPGTW" => Ok(Mnemonic::VPCMPGTW),
            "VPCMPISTRI" => Ok(Mnemonic::VPCMPISTRI),
            "VPCMPISTRM" => Ok(Mnemonic::VPCMPISTRM),
            "VPCMPQ" => Ok(Mnemonic::VPCMPQ),
            "VPCMPUB" => Ok(Mnemonic::VPCMPUB),
            "VPCMPUD" => Ok(Mnemonic::VPCMPUD),
            "VPCMPUQ" => Ok(Mnemonic::VPCMPUQ),
            "VPCMPUW" => Ok(Mnemonic::VPCMPUW),
            "VPCMPW" => Ok(Mnemonic::VPCMPW),
            "VPCOMPRESSD" => Ok(Mnemonic::VPCOMPRESSD),
            "VPCOMPRESSQ" => Ok(Mnemonic::VPCOMPRESSQ),
            "VPCONFLICTD" => Ok(Mnemonic::VPCONFLICTD),
            "VPCONFLICTQ" => Ok(Mnemonic::VPCONFLICTQ),
            "VPERM2F128" => Ok(Mnemonic::VPERM2F128),
            "VPERM2I128" => Ok(Mnemonic::VPERM2I128),
            "VPERMD" => Ok(Mnemonic::VPERMD),
            "VPERMI2D" => Ok(Mnemonic::VPERMI2D),
            "VPERMI2PD" => Ok(Mnemonic::VPERMI2PD),
            "VPERMI2PS" => Ok(Mnemonic::VPERMI2PS),
            "VPERMI2Q" => Ok(Mnemonic::VPERMI2Q),
            "VPERMI2W" => Ok(Mnemonic::VPERMI2W),
            "VPERMILPD" => Ok(Mnemonic::VPERMILPD),
            "VPERMILPS" => Ok(Mnemonic::VPERMILPS),
            "VPERMPD" => Ok(Mnemonic::VPERMPD),
            "VPERMPS" => Ok(Mnemonic::VPERMPS),
            "VPERMQ" => Ok(Mnemonic::VPERMQ),
            "VPERMT2D" => Ok(Mnemonic::VPERMT2D),
            "VPERMT2PD" => Ok(Mnemonic::VPERMT2PD),
            "VPERMT2PS" => Ok(Mnemonic::VPERMT2PS),
            "VPERMT2Q" => Ok(Mnemonic::VPERMT2Q),
            "VPERMT2W" => Ok(Mnemonic::VPERMT2W),
            "VPERMW" => Ok(Mnemonic::VPERMW),
            "VPEXPANDD" => Ok(Mnemonic::VPEXPANDD),
            "VPEXPANDQ" => Ok(Mnemonic::VPEXPANDQ),
            "VPEXTRB" => Ok(Mnemonic::VPEXTRB),
            "VPEXTRD" => Ok(Mnemonic::VPEXTRD),
            "VPEXTRQ" => Ok(Mnemonic::VPEXTRQ),
            "VPEXTRW" => Ok(Mnemonic::VPEXTRW),
            "VPGATHERDD" => Ok(Mnemonic::VPGATHERDD),
            "VPGATHERDQ" => Ok(Mnemonic::VPGATHERDQ),
            "VPGATHERQD" => Ok(Mnemonic::VPGATHERQD),
            "VPGATHERQQ" => Ok(Mnemonic::VPGATHERQQ),
            "VPHADDD" => Ok(Mnemonic::VPHADDD),
            "VPHADDSW" => Ok(Mnemonic::VPHADDSW),
            "VPHADDW" => Ok(Mnemonic::VPHADDW),
            "VPHMINPOSUW" => Ok(Mnemonic::VPHMINPOSUW),
            "VPHSUBD" => Ok(Mnemonic::VPHSUBD),
            "VPHSUBSW" => Ok(Mnemonic::VPHSUBSW),
            "VPHSUBW" => Ok(Mnemonic::VPHSUBW),
            "VPINSRB" => Ok(Mnemonic::VPINSRB),
            "VPINSRD" => Ok(Mnemonic::VPINSRD),
            "VPINSRQ" => Ok(Mnemonic::VPINSRQ),
            "VPINSRW" => Ok(Mnemonic::VPINSRW),
            "VPLZCNTD" => Ok(Mnemonic::VPLZCNTD),
            "VPLZCNTQ" => Ok(Mnemonic::VPLZCNTQ),
            "VPMADDUBSW" => Ok(Mnemonic::VPMADDUBSW),
            "VPMADDWD" => Ok(Mnemonic::VPMADDWD),
            "VPMASKMOVD" => Ok(Mnemonic::VPMASKMOVD),
            "VPMASKMOVQ" => Ok(Mnemonic::VPMASKMOVQ),
            "VPMAXSB" => Ok(Mnemonic::VPMAXSB),
            "VPMAXSD" => Ok(Mnemonic::VPMAXSD),
            "VPMAXSW" => Ok(Mnemonic::VPMAXSW),
            "VPMAXUB" => Ok(Mnemonic::VPMAXUB),
            "VPMAXUD" => Ok(Mnemonic::VPMAXUD),
            "VPMAXUQ" => Ok(Mnemonic::VPMAXUQ),
            "VPMAXUW" => Ok(Mnemonic::VPMAXUW),
            "VPMINSB" => Ok(Mnemonic::VPMINSB),
            "VPMINSD" => Ok(Mnemonic::VPMINSD),
            "VPMINSQ" => Ok(Mnemonic::VPMINSQ),
            "VPMINSW" => Ok(Mnemonic::VPMINSW),
            "VPMINUB" => Ok(Mnemonic::VPMINUB),
            "VPMINUD" => Ok(Mnemonic::VPMINUD),
            "VPMINUQ" => Ok(Mnemonic::VPMINUQ),
            "VPMINUW" => Ok(Mnemonic::VPMINUW),
            "VPMOVB2M" => Ok(Mnemonic::VPMOVB2M),
            "VPMOVD2M" => Ok(Mnemonic::VPMOVD2M),
            "VPMOVDB" => Ok(Mnemonic::VPMOVDB),
            "VPMOVDW" => Ok(Mnemonic::VPMOVDW),
            "VPMOVM2B" => Ok(Mnemonic::VPMOVM2B),
            "VPMOVM2D" => Ok(Mnemonic::VPMOVM2D),
            "VPMOVM2Q" => Ok(Mnemonic::VPMOVM2Q),
            "VPMOVM2W" => Ok(Mnemonic::VPMOVM2W),
            "VPMOVMSKB" => Ok(Mnemonic::VPMOVMSKB),
            "VPMOVQ2M" => Ok(Mnemonic::VPMOVQ2M),
            "VPMOVQB" => Ok(Mnemonic::VPMOVQB),
            "VPMOVQD" => Ok(Mnemonic::VPMOVQD),
            "VPMOVQW" => Ok(Mnemonic::VPMOVQW),
            "VPMOVSDB" => Ok(Mnemonic::VPMOVSDB),
            "VPMOVSDW" => Ok(Mnemonic::VPMOVSDW),
            "VPMOVSQB" => Ok(Mnemonic::VPMOVSQB),
            "VPMOVSQD" => Ok(Mnemonic::VPMOVSQD),
            "VPMOVSQW" => Ok(Mnemonic::VPMOVSQW),
            "VPMOVSWB" => Ok(Mnemonic::VPMOVSWB),
            "VPMOVSXBD" => Ok(Mnemonic::VPMOVSXBD),
            "VPMOVSXBQ" => Ok(Mnemonic::VPMOVSXBQ),
            "VPMOVSXBW" => Ok(Mnemonic::VPMOVSXBW),
            "VPMOVSXDQ" => Ok(Mnemonic::VPMOVSXDQ),
            "VPMOVSXWD" => Ok(Mnemonic::VPMOVSXWD),
            "VPMOVSXWQ" => Ok(Mnemonic::VPMOVSXWQ),
            "VPMOVUSDB" => Ok(Mnemonic::VPMOVUSDB),
            "VPMOVUSDW" => Ok(Mnemonic::VPMOVUSDW),
            "VPMOVUSQB" => Ok(Mnemonic::VPMOVUSQB),
            "VPMOVUSQD" => Ok(Mnemonic::VPMOVUSQD),
            "VPMOVUSQW" => Ok(Mnemonic::VPMOVUSQW),
            "VPMOVUSWB" => Ok(Mnemonic::VPMOVUSWB),
            "VPMOVW2M" => Ok(Mnemonic::VPMOVW2M),
            "VPMOVWB" => Ok(Mnemonic::VPMOVWB),
            "VPMOVZXBD" => Ok(Mnemonic::VPMOVZXBD),
            "VPMOVZXBQ" => Ok(Mnemonic::VPMOVZXBQ),
            "VPMOVZXBW" => Ok(Mnemonic::VPMOVZXBW),
            "VPMOVZXDQ" => Ok(Mnemonic::VPMOVZXDQ),
            "VPMOVZXWD" => Ok(Mnemonic::VPMOVZXWD),
            "VPMOVZXWQ" => Ok(Mnemonic::VPMOVZXWQ),
            "VPMULDQ" => Ok(Mnemonic::VPMULDQ),
            "VPMULHRSW" => Ok(Mnemonic::VPMULHRSW),
            "VPMULHUW" => Ok(Mnemonic::VPMULHUW),
            "VPMULHW" => Ok(Mnemonic::VPMULHW),
            "VPMULLD" => Ok(Mnemonic::VPMULLD),
            "VPMULLQ" => Ok(Mnemonic::VPMULLQ),
            "VPMULLW" => Ok(Mnemonic::VPMULLW),
            "VPMULUDQ" => Ok(Mnemonic::VPMULUDQ),
            "VPOR" => Ok(Mnemonic::VPOR),
            "VPORD" => Ok(Mnemonic::VPORD),
            "VPORQ" => Ok(Mnemonic::VPORQ),
            "VPROLD" => Ok(Mnemonic::VPROLD),
            "VPROLQ" => Ok(Mnemonic::VPROLQ),
            "VPROLVD" => Ok(Mnemonic::VPROLVD),
            "VPROLVQ" => Ok(Mnemonic::VPROLVQ),
            "VPRORD" => Ok(Mnemonic::VPRORD),
            "VPRORQ" => Ok(Mnemonic::VPRORQ),
            "VPRORVD" => Ok(Mnemonic::VPRORVD),
            "VPRORVQ" => Ok(Mnemonic::VPRORVQ),
            "VPSADBW" => Ok(Mnemonic::VPSADBW),
            "VPSCATTERDD" => Ok(Mnemonic::VPSCATTERDD),
            "VPSCATTERDQ" => Ok(Mnemonic::VPSCATTERDQ),
            "VPSCATTERQD" => Ok(Mnemonic::VPSCATTERQD),
            "VPSCATTERQQ" => Ok(Mnemonic::VPSCATTERQQ),
            "VPSHUFB" => Ok(Mnemonic::VPSHUFB),
            "VPSHUFD" => Ok(Mnemonic::VPSHUFD),
            "VPSHUFHW" => Ok(Mnemonic::VPSHUFHW),
            "VPSHUFLW" => Ok(Mnemonic::VPSHUFLW),
            "VPSIGNB" => Ok(Mnemonic::VPSIGNB),
            "VPSIGND" => Ok(Mnemonic::VPSIGND),
            "VPSIGNW" => Ok(Mnemonic::VPSIGNW),
            "VPSLLD" => Ok(Mnemonic::VPSLLD),
            "VPSLLDQ" => Ok(Mnemonic::VPSLLDQ),
            "VPSLLQ" => Ok(Mnemonic::VPSLLQ),
            "VPSLLVD" => Ok(Mnemonic::VPSLLVD),
            "VPSLLVQ" => Ok(Mnemonic::VPSLLVQ),
            "VPSLLVW" => Ok(Mnemonic::VPSLLVW),
            "VPSLLW" => Ok(Mnemonic::VPSLLW),
            "VPSRAD" => Ok(Mnemonic::VPSRAD),
            "VPSRAQ" => Ok(Mnemonic::VPSRAQ),
            "VPSRAVD" => Ok(Mnemonic::VPSRAVD),
            "VPSRAVQ" => Ok(Mnemonic::VPSRAVQ),
            "VPSRAVW" => Ok(Mnemonic::VPSRAVW),
            "VPSRAW" => Ok(Mnemonic::VPSRAW),
            "VPSRLD" => Ok(Mnemonic::VPSRLD),
            "VPSRLDQ" => Ok(Mnemonic::VPSRLDQ),
            "VPSRLQ" => Ok(Mnemonic::VPSRLQ),
            "VPSRLVD" => Ok(Mnemonic::VPSRLVD),
            "VPSRLVQ" => Ok(Mnemonic::VPSRLVQ),
            "VPSRLVW" => Ok(Mnemonic::VPSRLVW),
            "VPSRLW" => Ok(Mnemonic::VPSRLW),
            "VPSUBB" => Ok(Mnemonic::VPSUBB),
            "VPSUBD" => Ok(Mnemonic::VPSUBD),
            "VPSUBQ" => Ok(Mnemonic::VPSUBQ),
            "VPSUBSB" => Ok(Mnemonic::VPSUBSB),
            "VPSUBSW" => Ok(Mnemonic::VPSUBSW),
            "VPSUBUSB" => Ok(Mnemonic::VPSUBUSB),
            "VPSUBUSW" => Ok(Mnemonic::VPSUBUSW),
            "VPSUBW" => Ok(Mnemonic::VPSUBW),
            "VPTERNLOGD" => Ok(Mnemonic::VPTERNLOGD),
            "VPTERNLOGQ" => Ok(Mnemonic::VPTERNLOGQ),
            "VPTEST" => Ok(Mnemonic::VPTEST),
            "VPTESTMB" => Ok(Mnemonic::VPTESTMB),
            "VPTESTMD" => Ok(Mnemonic::VPTESTMD),
            "VPTESTMQ" => Ok(Mnemonic::VPTESTMQ),
            "VPTESTMW" => Ok(Mnemonic::VPTESTMW),
            "VPTESTNMB" => Ok(Mnemonic::VPTESTNMB),
            "VPTESTNMD" => Ok(Mnemonic::VPTESTNMD),
            "VPTESTNMQ" => Ok(Mnemonic::VPTESTNMQ),
            "VPTESTNMW" => Ok(Mnemonic::VPTESTNMW),
            "VPUNPCKHBW" => Ok(Mnemonic::VPUNPCKHBW),
            "VPUNPCKHDQ" => Ok(Mnemonic::VPUNPCKHDQ),
            "VPUNPCKHQDQ" => Ok(Mnemonic::VPUNPCKHQDQ),
            "VPUNPCKHWD" => Ok(Mnemonic::VPUNPCKHWD),
            "VPUNPCKLBW" => Ok(Mnemonic::VPUNPCKLBW),
            "VPUNPCKLDQ" => Ok(Mnemonic::VPUNPCKLDQ),
            "VPUNPCKLQDQ" => Ok(Mnemonic::VPUNPCKLQDQ),
            "VPUNPCKLWD" => Ok(Mnemonic::VPUNPCKLWD),
            "VPXOR" => Ok(Mnemonic::VPXOR),
            "VPXORD" => Ok(Mnemonic::VPXORD),
            "VPXORQ" => Ok(Mnemonic::VPXORQ),
            "VRANGEPD" => Ok(Mnemonic::VRANGEPD),
            "VRANGEPS" => Ok(Mnemonic::VRANGEPS),
            "VRANGESD" => Ok(Mnemonic::VRANGESD),
            "VRANGESS" => Ok(Mnemonic::VRANGESS),
            "VRCP14PD" => Ok(Mnemonic::VRCP14PD),
            "VRCP14PS" => Ok(Mnemonic::VRCP14PS),
            "VRCP14SD" => Ok(Mnemonic::VRCP14SD),
            "VRCP14SS" => Ok(Mnemonic::VRCP14SS),
            "VRCP28PD" => Ok(Mnemonic::VRCP28PD),
            "VRCP28PS" => Ok(Mnemonic::VRCP28PS),
            "VRCP28SD" => Ok(Mnemonic::VRCP28SD),
            "VRCP28SS" => Ok(Mnemonic::VRCP28SS),
            "VRCPPS" => Ok(Mnemonic::VRCPPS),
            "VRCPSS" => Ok(Mnemonic::VRCPSS),
            "VREDUCEPD" => Ok(Mnemonic::VREDUCEPD),
            "VREDUCEPS" => Ok(Mnemonic::VREDUCEPS),
            "VREDUCESD" => Ok(Mnemonic::VREDUCESD),
            "VREDUCESS" => Ok(Mnemonic::VREDUCESS),
            "VRNDSCALEPD" => Ok(Mnemonic::VRNDSCALEPD),
            "VRNDSCALEPS" => Ok(Mnemonic::VRNDSCALEPS),
            "VRNDSCALESD" => Ok(Mnemonic::VRNDSCALESD),
            "VRNDSCALESS" => Ok(Mnemonic::VRNDSCALESS),
            "VROUNDPD" => Ok(Mnemonic::VROUNDPD),
            "VROUNDPS" => Ok(Mnemonic::VROUNDPS),
            "VROUNDSD" => Ok(Mnemonic::VROUNDSD),
            "VROUNDSS" => Ok(Mnemonic::VROUNDSS),
            "VRSQRT14PD" => Ok(Mnemonic::VRSQRT14PD),
            "VRSQRT14PS" => Ok(Mnemonic::VRSQRT14PS),
            "VRSQRT14SD" => Ok(Mnemonic::VRSQRT14SD),
            "VRSQRT14SS" => Ok(Mnemonic::VRSQRT14SS),
            "VRSQRT28PD" => Ok(Mnemonic::VRSQRT28PD),
            "VRSQRT28PS" => Ok(Mnemonic::VRSQRT28PS),
            "VRSQRT28SD" => Ok(Mnemonic::VRSQRT28SD),
            "VRSQRT28SS" => Ok(Mnemonic::VRSQRT28SS),
            "VRSQRTPS" => Ok(Mnemonic::VRSQRTPS),
            "VRSQRTSS" => Ok(Mnemonic::VRSQRTSS),
            "VSCALEFPD" => Ok(Mnemonic::VSCALEFPD),
            "VSCALEFPS" => Ok(Mnemonic::VSCALEFPS),
            "VSCALEFSD" => Ok(Mnemonic::VSCALEFSD),
            "VSCALEFSS" => Ok(Mnemonic::VSCALEFSS),
            "VSCATTERDPD" => Ok(Mnemonic::VSCATTERDPD),
            "VSCATTERDPS" => Ok(Mnemonic::VSCATTERDPS),
            "VSCATTERPF0DPD" => Ok(Mnemonic::VSCATTERPF0DPD),
            "VSCATTERPF0DPS" => Ok(Mnemonic::VSCATTERPF0DPS),
            "VSCATTERPF0QPD" => Ok(Mnemonic::VSCATTERPF0QPD),
            "VSCATTERPF0QPS" => Ok(Mnemonic::VSCATTERPF0QPS),
            "VSCATTERPF1DPD" => Ok(Mnemonic::VSCATTERPF1DPD),
            "VSCATTERPF1DPS" => Ok(Mnemonic::VSCATTERPF1DPS),
            "VSCATTERPF1QPD" => Ok(Mnemonic::VSCATTERPF1QPD),
            "VSCATTERPF1QPS" => Ok(Mnemonic::VSCATTERPF1QPS),
            "VSCATTERQPD" => Ok(Mnemonic::VSCATTERQPD),
            "VSCATTERQPS" => Ok(Mnemonic::VSCATTERQPS),
            "VSHUFF32x4" => Ok(Mnemonic::VSHUFF32x4),
            "VSHUFF64x2" => Ok(Mnemonic::VSHUFF64x2),
            "VSHUFI32x4" => Ok(Mnemonic::VSHUFI32x4),
            "VSHUFI64x2" => Ok(Mnemonic::VSHUFI64x2),
            "VSHUFPD" => Ok(Mnemonic::VSHUFPD),
            "VSHUFPS" => Ok(Mnemonic::VSHUFPS),
            "VSQRTPD" => Ok(Mnemonic::VSQRTPD),
            "VSQRTPS" => Ok(Mnemonic::VSQRTPS),
            "VSQRTSD" => Ok(Mnemonic::VSQRTSD),
            "VSQRTSS" => Ok(Mnemonic::VSQRTSS),
            "VSTMXCSR" => Ok(Mnemonic::VSTMXCSR),
            "VSUBPD" => Ok(Mnemonic::VSUBPD),
            "VSUBPS" => Ok(Mnemonic::VSUBPS),
            "VSUBSD" => Ok(Mnemonic::VSUBSD),
            "VSUBSS" => Ok(Mnemonic::VSUBSS),
            "VTESTPD" => Ok(Mnemonic::VTESTPD),
            "VTESTPS" => Ok(Mnemonic::VTESTPS),
            "VUCOMISD" => Ok(Mnemonic::VUCOMISD),
            "VUCOMISS" => Ok(Mnemonic::VUCOMISS),
            "VUNPCKHPD" => Ok(Mnemonic::VUNPCKHPD),
            "VUNPCKHPS" => Ok(Mnemonic::VUNPCKHPS),
            "VUNPCKLPD" => Ok(Mnemonic::VUNPCKLPD),
            "VUNPCKLPS" => Ok(Mnemonic::VUNPCKLPS),
            "VXORPD" => Ok(Mnemonic::VXORPD),
            "VXORPS" => Ok(Mnemonic::VXORPS),
            "VZEROALL" => Ok(Mnemonic::VZEROALL),
            "VZEROUPPER" => Ok(Mnemonic::VZEROUPPER),
            "WAIT" => Ok(Mnemonic::WAIT),
            "WBINVD" => Ok(Mnemonic::WBINVD),
            "WRFSBASE" => Ok(Mnemonic::WRFSBASE),
            "WRGSBASE" => Ok(Mnemonic::WRGSBASE),
            "WRMSR" => Ok(Mnemonic::WRMSR),
            "WRPKRU" => Ok(Mnemonic::WRPKRU),
            "XABORT" => Ok(Mnemonic::XABORT),
            "XACQUIRE" => Ok(Mnemonic::XACQUIRE),
            "XADD" => Ok(Mnemonic::XADD),
            "XBEGIN" => Ok(Mnemonic::XBEGIN),
            "XCHG" => Ok(Mnemonic::XCHG),
            "XEND" => Ok(Mnemonic::XEND),
            "XGETBV" => Ok(Mnemonic::XGETBV),
            "XLAT" => Ok(Mnemonic::XLAT),
            "XLATB" => Ok(Mnemonic::XLATB),
            "XOR" => Ok(Mnemonic::XOR),
            "XORPD" => Ok(Mnemonic::XORPD),
            "XORPS" => Ok(Mnemonic::XORPS),
            "XRELEASE" => Ok(Mnemonic::XRELEASE),
            "XRSTOR" => Ok(Mnemonic::XRSTOR),
            "XRSTOR64" => Ok(Mnemonic::XRSTOR64),
            "XRSTORS" => Ok(Mnemonic::XRSTORS),
            "XRSTORS64" => Ok(Mnemonic::XRSTORS64),
            "XSAVE" => Ok(Mnemonic::XSAVE),
            "XSAVE64" => Ok(Mnemonic::XSAVE64),
            "XSAVEC" => Ok(Mnemonic::XSAVEC),
            "XSAVEC64" => Ok(Mnemonic::XSAVEC64),
            "XSAVEOPT" => Ok(Mnemonic::XSAVEOPT),
            "XSAVEOPT64" => Ok(Mnemonic::XSAVEOPT64),
            "XSAVES" => Ok(Mnemonic::XSAVES),
            "XSAVES64" => Ok(Mnemonic::XSAVES64),
            "XSETBV" => Ok(Mnemonic::XSETBV),
            "XTEST" => Ok(Mnemonic::XTEST),
            _ => Err(())
        }
    }
}
